var A=Object.defineProperty;var p=Object.getOwnPropertySymbols;var w=Object.prototype.hasOwnProperty,K=Object.prototype.propertyIsEnumerable;var y=(t,s,l)=>s in t?A(t,s,{enumerable:!0,configurable:!0,writable:!0,value:l}):t[s]=l,c=(t,s)=>{for(var l in s||(s={}))w.call(s,l)&&y(t,l,s[l]);if(p)for(var l of p(s))K.call(s,l)&&y(t,l,s[l]);return t};import{r as x,j as e}from"./index-1.0.0.js";import{_ as a,L as P,N as I}from"./bi-895-8.js";import{f as z}from"./bi-88-17.js";function f({klaviyoConf:t,setKlaviyoConf:s,step:l,setStep:k,isInfo:r,loading:n,setLoading:g}){const[i,j]=x.useState(!1),[o,d]=x.useState({name:"",authKey:""}),h=m=>{const u=c({},t),b=c({},o);b[m.target.name]="",u[m.target.name]=m.target.value,d(b),s(u)},v=()=>{setTimeout(()=>{document.getElementById("btcd-settings-wrp").scrollTop=0},300),k(2)},N=`
  <h4>${a("Step of get API Key:","elementor-klaviyo")}</h4>
  <ul>
    <li>${a("Go to Settings and click on","elementor-klaviyo")} <a href="https://www.klaviyo.com/account#api-keys-tab" target='_blank'>${a("API Keys.","elementor-klaviyo")}</a></li>
    <li>${a("Click on Create Private API key.","elementor-klaviyo")}</li>
    <li>${a("Copy the <b>Private API Key</b> and paste into <b>API Key</b> field of your authorization form.","elementor-klaviyo")}</li>
    <li>${a("Finally, click <b>Authorize</b> button.","elementor-klaviyo")}</li>
</ul>
`;return e.jsx("div",{className:"btcd-stp-page",style:{width:l===1&&900,height:l===1&&"auto"},children:e.jsxs("div",{className:"mt-2",children:[e.jsx("div",{className:"my-1",children:e.jsx("b",{children:a("Integration Name:","elementor-klaviyo")})}),e.jsx("input",{className:"btcd-paper-inp w-6 mt-1 mx-0",onChange:h,name:"name",value:t==null?void 0:t.name,type:"text",placeholder:a("Integration Name...","elementor-klaviyo"),disabled:r}),e.jsx("div",{className:"mt-3",children:e.jsx("b",{children:a("API Key:","elementor-klaviyo")})}),e.jsx("input",{className:"btcd-paper-inp w-6 mt-1 mx-0",onChange:h,name:"authKey",value:t==null?void 0:t.authKey,type:"text",placeholder:a("API Key...","elementor-klaviyo"),disabled:r}),o.authKey&&e.jsx("div",{className:"mt-1 mb-2 error-msg",children:o.authKey}),e.jsxs("small",{className:"d-blk mt-5",children:[a("To get API key, please visit ","elementor-klaviyo"),e.jsx("a",{className:"btcd-link",href:"https://www.klaviyo.com/account#api-keys-tab",target:"_blank",rel:"noreferrer",children:a("here.","elementor-klaviyo")})]}),!r&&e.jsxs("div",{className:"w-6 d-flx flx-between ",children:[e.jsxs("button",{onClick:()=>z(t,s,d,j,n,g),className:"btn btcd-btn-lg green sh-sm",type:"button",disabled:i||n.auth,children:[i?a("Authorized ✔","elementor-klaviyo"):a("Authorize","elementor-klaviyo"),n.auth&&e.jsx(P,{size:"20",clr:"#022217",className:"ml-2"})]}),e.jsx("br",{}),e.jsxs("button",{onClick:v,className:"btn btcd-btn-lg green sh-sm",type:"button",disabled:!i,children:[a("Next","elementor-klaviyo"),e.jsx("div",{className:"btcd-icn icn-arrow_back rev-icn d-in-b"})]})]}),e.jsx(I,{note:N,className:"mt-5"})]})})}export{f as default};
