<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3928ba64545bb786c0e98440c240d5cd
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'BulkPriceEditor\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'BulkPriceEditor\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3928ba64545bb786c0e98440c240d5cd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3928ba64545bb786c0e98440c240d5cd::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3928ba64545bb786c0e98440c240d5cd::$classMap;

        }, null, ClassLoader::class);
    }
}
