<?php
/**
 * This is the default template part for a
 * product in the store.
 *
 * @since 0.4.0
 * @version CHANGEME
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
*/
?>

<?php
// process only if a product image exists
if ( it_exchange_product_has_feature( $GLOBALS['it_exchange']['product']->ID, 'product-images' )) {

    $product_id = $GLOBALS['it_exchange']['product']->ID;
    $product_title = $GLOBALS['it_exchange']['product']->post_title;
    $product_images = it_exchange_get_product_feature( $product_id, 'product-images' );

    $feature_image = array(
        'id'    => $product_images[0],
        'thumb' => wp_get_attachment_thumb_url( $product_images[0] ),
        'large' => wp_get_attachment_url( $product_images[0] )
    );
?>  

    <?php do_action( 'it_exchange_content_store_before_product_element' ); ?>
    <li class="it-exchange-product gis-item is-collapsed <?php it_exchange( 'store', 'product-classes' ); ?>">
        <?php do_action( 'it_exchange_content_store_begin_product_element' ); ?>

        <div class="gis-thumbnail">
            <a href="#expand-jump-<?php echo $product_id; ?>" class="gis-expand">
                <img id="expand-jump-<?php echo $product_id; ?>" class="it-exchange-product-feature-image" src="<?php echo $feature_image['large']; ?>" alt="<?php echo $product_title; ?>" title="<?php echo $product_title; ?>" />
            </a>
            <div class="arrow-up"></div>
        </div>

        <div class="gis-details">
            <a href="#close-jump-<?php echo $product_id; ?>" class="expand_close"></a>
            <div class="gis-details-left">
                <a href="<?php it_exchange( 'product', 'permalink', array( 'format' => 'url' ) ); ?>"><img class="it-exchange-product-feature-image image-large" src="<?php echo $feature_image['large']; ?>" alt="<?php echo $product_title; ?>" title="<?php echo $product_title; ?>" /></a>
            </div>

            <div class="gis-details-right">
                <div class="it-exchange-product-details">
                    <?php it_exchange_get_template_part( 'content-store/loops/product-info' ); ?>
                </div>
            </div>
        </div>    

            <?php do_action( 'it_exchange_content_store_end_product_element' ); ?>
    </li>
    <?php do_action( 'it_exchange_content_store_after_product_element' ); ?>

<?php } // has images ?>