<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '1c1793a06aa4ce3b048d98cd7e408337' => $baseDir . '/app/Helpers/HelperFunctions.php',
);
