<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7e988a03fbffe9893b5755a660fe73f5
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static $classMap = array (
        'Autoblue\\Admin' => __DIR__ . '/../..' . '/includes/Admin.php',
        'Autoblue\\Assets' => __DIR__ . '/../..' . '/includes/Assets.php',
        'Autoblue\\Blocks' => __DIR__ . '/../..' . '/includes/Blocks.php',
        'Autoblue\\Bluesky' => __DIR__ . '/../..' . '/includes/Bluesky.php',
        'Autoblue\\Bluesky\\API' => __DIR__ . '/../..' . '/includes/Bluesky/API.php',
        'Autoblue\\Bluesky\\TextParser' => __DIR__ . '/../..' . '/includes/Bluesky/TextParser.php',
        'Autoblue\\CLI\\Commands' => __DIR__ . '/../..' . '/includes/CLI/Commands.php',
        'Autoblue\\CLI\\Logs' => __DIR__ . '/../..' . '/includes/CLI/Logs.php',
        'Autoblue\\Comments' => __DIR__ . '/../..' . '/includes/Comments.php',
        'Autoblue\\ConnectionsManager' => __DIR__ . '/../..' . '/includes/ConnectionsManager.php',
        'Autoblue\\Endpoints\\AccountController' => __DIR__ . '/../..' . '/includes/Endpoints/AccountController.php',
        'Autoblue\\Endpoints\\ConnectionsController' => __DIR__ . '/../..' . '/includes/Endpoints/ConnectionsController.php',
        'Autoblue\\Endpoints\\LogsController' => __DIR__ . '/../..' . '/includes/Endpoints/LogsController.php',
        'Autoblue\\Endpoints\\SearchController' => __DIR__ . '/../..' . '/includes/Endpoints/SearchController.php',
        'Autoblue\\ImageCompressor' => __DIR__ . '/../..' . '/includes/ImageCompressor.php',
        'Autoblue\\Logging\\DatabaseHandler' => __DIR__ . '/../..' . '/includes/Logging/DatabaseHandler.php',
        'Autoblue\\Logging\\Log' => __DIR__ . '/../..' . '/includes/Logging/Log.php',
        'Autoblue\\Logging\\LogRepository' => __DIR__ . '/../..' . '/includes/Logging/LogRepository.php',
        'Autoblue\\Logging\\Setup' => __DIR__ . '/../..' . '/includes/Logging/Setup.php',
        'Autoblue\\Logging\\WPProcessor' => __DIR__ . '/../..' . '/includes/Logging/WPProcessor.php',
        'Autoblue\\Meta' => __DIR__ . '/../..' . '/includes/Meta.php',
        'Autoblue\\PostHandler' => __DIR__ . '/../..' . '/includes/PostHandler.php',
        'Autoblue\\Setup' => __DIR__ . '/../..' . '/includes/Setup.php',
        'Autoblue\\Utils' => __DIR__ . '/../..' . '/includes/Utils.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7e988a03fbffe9893b5755a660fe73f5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7e988a03fbffe9893b5755a660fe73f5::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7e988a03fbffe9893b5755a660fe73f5::$classMap;

        }, null, ClassLoader::class);
    }
}
