<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AIContentWriter\\Admin\\Actions' => $baseDir . '/includes/Admin/Actions.php',
    'AIContentWriter\\Admin\\Admin' => $baseDir . '/includes/Admin/Admin.php',
    'AIContentWriter\\Plugin' => $baseDir . '/includes/Plugin.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
