<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6efcfd3443ef5290e485b36aa6b64a8b
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'AIContentWriter\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'AIContentWriter\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'AIContentWriter\\Admin\\Actions' => __DIR__ . '/../..' . '/includes/Admin/Actions.php',
        'AIContentWriter\\Admin\\Admin' => __DIR__ . '/../..' . '/includes/Admin/Admin.php',
        'AIContentWriter\\Plugin' => __DIR__ . '/../..' . '/includes/Plugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6efcfd3443ef5290e485b36aa6b64a8b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6efcfd3443ef5290e485b36aa6b64a8b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6efcfd3443ef5290e485b36aa6b64a8b::$classMap;

        }, null, ClassLoader::class);
    }
}
