<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3474fa0427a4b83b8e837548c9546c3e
{
    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\' => 49,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\' => 
        array (
            0 => __DIR__ . '/..' . '/krokedil/woocommerce/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Base' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Base.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\Cart' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/Cart.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartCustomer.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineCoupon.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineFee.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineItem.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Cart\\CartLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineShipping.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Abstracts\\AbstractGiftCardCompatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Abstracts/AbstractGiftCardCompatibility.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Compatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Compatibility.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\PWGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/PWGiftCards.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\SmartCoupons' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/SmartCoupons.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\WCGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/WCGiftCards.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\YITHGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/YITHGiftCards.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\CustomerData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/CustomerData.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\CompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/CompatibilityInterface.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\GiftCardCompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/GiftCardCompatibilityInterface.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Interfaces\\MetaboxInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/MetaboxInterface.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\KrokedilWooCommerce' => __DIR__ . '/..' . '/krokedil/woocommerce/src/KrokedilWooCommerce.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\OrderData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderData.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\OrderLineData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderLineData.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\OrderMetabox' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderMetabox.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Order\\Order' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/Order.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderCustomer.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLine' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLine.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineCoupon.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineFee.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineItem.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\Order\\OrderLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineShipping.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApi' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApi.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiCustomer.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineCoupon.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineFee.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineItem.php',
        'KrokedilQvicklyCheckoutDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineShipping.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3474fa0427a4b83b8e837548c9546c3e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3474fa0427a4b83b8e837548c9546c3e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3474fa0427a4b83b8e837548c9546c3e::$classMap;

        }, null, ClassLoader::class);
    }
}
