<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'TARecord\\LocationAddonForGravityForms\\Core' => $baseDir . '/src/Core.php',
    'TARecord\\LocationAddonForGravityForms\\Database' => $baseDir . '/src/Database.php',
    'TARecord\\LocationAddonForGravityForms\\FormLocationsTable' => $baseDir . '/src/FormLocationsTable.php',
    'TARecord\\LocationAddonForGravityForms\\Relationship' => $baseDir . '/src/Relationship.php',
    'TARecord\\LocationAddonForGravityForms\\Scan' => $baseDir . '/src/Scan.php',
    'TARecord\\LocationAddonForGravityForms\\Settings' => $baseDir . '/src/Settings.php',
);
