<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1507ba7fedb878d228d34d4cc9ef57e8
{
    public static $files = array (
        '7d88166f7223e12d726367cc1c928fca' => __DIR__ . '/..' . '/ua1-labs/firebug/functions.php',
        '87e500a6ffd9d76e744f97d99e8ba8c3' => __DIR__ . '/..' . '/ua1-labs/firesql/init.php',
    );

    public static $prefixLengthsPsr4 = array (
        'U' => 
        array (
            'UA1Labs\\' => 8,
        ),
        'P' => 
        array (
            'Psr\\Container\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'UA1Labs\\' => 
        array (
            0 => __DIR__ . '/..' . '/ua1-labs/firebug/UA1Labs',
            1 => __DIR__ . '/..' . '/ua1-labs/firedi/UA1Labs',
            2 => __DIR__ . '/..' . '/ua1-labs/firesql/UA1Labs',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1507ba7fedb878d228d34d4cc9ef57e8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1507ba7fedb878d228d34d4cc9ef57e8::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
