<?php return array(
    'root' => array(
        'name' => 'alibabacloud/vod-20170321',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'adbario/php-dot-notation' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => '081e2cca50c84bfeeea2e3ef9b2c8d206d80ccae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../adbario/php-dot-notation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/credentials' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'ebcda2e628180b4df235b46a86e1d014c561f5d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alibabacloud/credentials',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/darabonba-openapi' => array(
            'pretty_version' => '0.2.13',
            'version' => '0.2.13.0',
            'reference' => '0213396384e2c064eefd614f3dd53636a63f987f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alibabacloud/darabonba-openapi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/endpoint-util' => array(
            'pretty_version' => '0.1.1',
            'version' => '0.1.1.0',
            'reference' => 'f3fe88a25d8df4faa3b0ae14ff202a9cc094e6c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alibabacloud/endpoint-util',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/gateway-spi' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '7440f77750c329d8ab252db1d1d967314ccd1fcb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alibabacloud/gateway-spi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/openapi-util' => array(
            'pretty_version' => '0.2.1',
            'version' => '0.2.1.0',
            'reference' => 'f31f7bcd835e08ca24b6b8ba33637eb4eceb093a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alibabacloud/openapi-util',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/tea' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '1619cb96c158384f72b873e1f85de8b299c9c367',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alibabacloud/tea',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/tea-utils' => array(
            'pretty_version' => '0.2.21',
            'version' => '0.2.21.0',
            'reference' => '5039e45714c6456186d267f5d81a4b260a652495',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alibabacloud/tea-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/tea-xml' => array(
            'pretty_version' => '0.2.4',
            'version' => '0.2.4.0',
            'reference' => '3e0c000bf536224eebbac913c371bef174c0a16a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alibabacloud/tea-xml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alibabacloud/vod-20170321' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.9.2',
            'version' => '7.9.2.0',
            'reference' => 'd281ed313b989f213357e3be1a179f02196ac99b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '6ea8dd08867a2a42619d65c3deb2c0fcbf81c8f8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => 'a70f5c95fb43bc83f07c9c948baa0dc1829bf201',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lizhichao/one-sm' => array(
            'pretty_version' => '1.10',
            'version' => '1.10.0.0',
            'reference' => '687a012a44a5bfd4d9143a0234e1060543be455a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lizhichao/one-sm',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
