<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite0b81da6b50b22cd85691340976a3064
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'Optemiz\\Dashboard\\' => 18,
            'Optemiz\\AWO\\' => 12,
        ),
        'A' => 
        array (
            'Automattic\\Jetpack\\Autoloader\\' => 30,
            'Appsero\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Optemiz\\Dashboard\\' => 
        array (
            0 => __DIR__ . '/..' . '/optemiz/dashboard/includes',
        ),
        'Optemiz\\AWO\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
        'Automattic\\Jetpack\\Autoloader\\' => 
        array (
            0 => __DIR__ . '/..' . '/automattic/jetpack-autoloader/src',
        ),
        'Appsero\\' => 
        array (
            0 => __DIR__ . '/..' . '/appsero/client/src',
        ),
    );

    public static $classMap = array (
        'Appsero\\Client' => __DIR__ . '/..' . '/appsero/client/src/Client.php',
        'Appsero\\Insights' => __DIR__ . '/..' . '/appsero/client/src/Insights.php',
        'Appsero\\License' => __DIR__ . '/..' . '/appsero/client/src/License.php',
        'Automattic\\Jetpack\\Autoloader\\AutoloadFileWriter' => __DIR__ . '/..' . '/automattic/jetpack-autoloader/src/AutoloadFileWriter.php',
        'Automattic\\Jetpack\\Autoloader\\AutoloadGenerator' => __DIR__ . '/..' . '/automattic/jetpack-autoloader/src/AutoloadGenerator.php',
        'Automattic\\Jetpack\\Autoloader\\AutoloadProcessor' => __DIR__ . '/..' . '/automattic/jetpack-autoloader/src/AutoloadProcessor.php',
        'Automattic\\Jetpack\\Autoloader\\CustomAutoloaderPlugin' => __DIR__ . '/..' . '/automattic/jetpack-autoloader/src/CustomAutoloaderPlugin.php',
        'Automattic\\Jetpack\\Autoloader\\ManifestGenerator' => __DIR__ . '/..' . '/automattic/jetpack-autoloader/src/ManifestGenerator.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Optemiz\\AWO\\Admin' => __DIR__ . '/../..' . '/includes/Admin.php',
        'Optemiz\\AWO\\Admin_Menu' => __DIR__ . '/../..' . '/includes/Admin_Menu.php',
        'Optemiz\\AWO\\Admin_Notices' => __DIR__ . '/../..' . '/includes/Admin_Notices.php',
        'Optemiz\\AWO\\Admin_Page' => __DIR__ . '/../..' . '/includes/Admin_Page.php',
        'Optemiz\\AWO\\Assets' => __DIR__ . '/../..' . '/includes/Assets.php',
        'Optemiz\\AWO\\AutoComplete_Orders' => __DIR__ . '/../..' . '/includes/AutoComplete_Orders.php',
        'Optemiz\\AWO\\Frontend' => __DIR__ . '/../..' . '/includes/Frontend.php',
        'Optemiz\\AWO\\Metaboxes' => __DIR__ . '/../..' . '/includes/Metaboxes.php',
        'Optemiz\\AWO\\Settings' => __DIR__ . '/../..' . '/includes/Settings.php',
        'Optemiz\\Dashboard\\AbstractField' => __DIR__ . '/..' . '/optemiz/dashboard/includes/AbstractField.php',
        'Optemiz\\Dashboard\\AbstractTab' => __DIR__ . '/..' . '/optemiz/dashboard/includes/AbstractTab.php',
        'Optemiz\\Dashboard\\Field' => __DIR__ . '/..' . '/optemiz/dashboard/includes/Field.php',
        'Optemiz\\Dashboard\\Header' => __DIR__ . '/..' . '/optemiz/dashboard/includes/Header.php',
        'Optemiz\\Dashboard\\Settings' => __DIR__ . '/..' . '/optemiz/dashboard/includes/Settings.php',
        'Optemiz\\Dashboard\\Sidebar' => __DIR__ . '/..' . '/optemiz/dashboard/includes/Sidebar.php',
        'Optemiz\\Dashboard\\SubTab' => __DIR__ . '/..' . '/optemiz/dashboard/includes/SubTab.php',
        'Optemiz\\Dashboard\\Tab' => __DIR__ . '/..' . '/optemiz/dashboard/includes/Tab.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite0b81da6b50b22cd85691340976a3064::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite0b81da6b50b22cd85691340976a3064::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite0b81da6b50b22cd85691340976a3064::$classMap;

        }, null, ClassLoader::class);
    }
}
