<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb2278d98629c5d3498d64528ec5f980d
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DatalayerForWoocommerceFree\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DatalayerForWoocommerceFree\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb2278d98629c5d3498d64528ec5f980d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb2278d98629c5d3498d64528ec5f980d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb2278d98629c5d3498d64528ec5f980d::$classMap;

        }, null, ClassLoader::class);
    }
}
