<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'JUVO_MailEditor\Dependencies\Symfony\Polyfill\Mbstring\Mbstring' => $strauss_src . '/symfony/polyfill-mbstring/Mbstring.php',
   'JUVO_MailEditor\Dependencies\Symfony\Polyfill\Ctype\Ctype' => $strauss_src . '/symfony/polyfill-ctype/Ctype.php',
   'ReturnTypeWillChange' => $strauss_src . '/symfony/polyfill-php81/Resources/stubs/ReturnTypeWillChange.php',
   'CURLStringFile' => $strauss_src . '/symfony/polyfill-php81/Resources/stubs/CURLStringFile.php',
   'JUVO_MailEditor\Dependencies\Symfony\Polyfill\Php81\Php81' => $strauss_src . '/symfony/polyfill-php81/Php81.php',
);