<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9ad7fca926a9df6fc26bf57cea9fa859
{
    public static $prefixesPsr0 = array (
        'H' => 
        array (
            'Hametuha\\Hamecache' => 
            array (
                0 => __DIR__ . '/../..' . '/app',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit9ad7fca926a9df6fc26bf57cea9fa859::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
