<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4fab6b48d3140911f83a7e252606a3c9
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Automattic\\WooCommerce\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Automattic\\WooCommerce\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/WooCommerce',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4fab6b48d3140911f83a7e252606a3c9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4fab6b48d3140911f83a7e252606a3c9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4fab6b48d3140911f83a7e252606a3c9::$classMap;

        }, null, ClassLoader::class);
    }
}
