<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'UA1Labs\\' => array($vendorDir . '/ua1-labs/firebug/UA1Labs', $vendorDir . '/ua1-labs/firedi/UA1Labs', $vendorDir . '/ua1-labs/firesql/UA1Labs'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
);
