<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '469f3932524c072f641a13b4d4d52480dd6079d8',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '469f3932524c072f641a13b4d4d52480dd6079d8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.5.5',
            'version' => '1.5.5.0',
            'reference' => '08c50d5ec4c6ced7d0271d2862dec8c1033283e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'freemius/wordpress-sdk' => array(
            'pretty_version' => '2.11.0',
            'version' => '2.11.0.0',
            'reference' => '9ad5477e4f0a39999b96bb21d0327bc6841d4590',
            'type' => 'library',
            'install_path' => __DIR__ . '/../freemius/wordpress-sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geoip2/geoip2' => array(
            'pretty_version' => 'v2.13.0',
            'version' => '2.13.0.0',
            'reference' => '6a41d8fbd6b90052bc34dff3b4252d0f88067b23',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geoip2/geoip2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maxmind-db/reader' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => '5b2d7a721dedfaef9dc20822c5fe7d26f9f8eb90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind-db/reader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maxmind/web-service-common' => array(
            'pretty_version' => 'v0.9.0',
            'version' => '0.9.0.0',
            'reference' => '4dc5a3e8df38aea4ca3b1096cee3a038094e9b53',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind/web-service-common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
