<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd90ac2544babe18e78ecb025e2b7d235
{
    public static $files = array (
        '65e023e5408b48c8a4eaebc6305d0f67' => __DIR__ . '/../..' . '/includes/core.php',
        'da21c6669493ba905cb2932f5e08db45' => __DIR__ . '/../..' . '/includes/codestar/codestar-framework.php',
    );

    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Bright_Delivery_for_Woocommerce\\' => 32,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Bright_Delivery_for_Woocommerce\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd90ac2544babe18e78ecb025e2b7d235::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd90ac2544babe18e78ecb025e2b7d235::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
