<option value="website">Website</option>
<option value="business.business">Business</option>
<option value="product">Product</option>
<option value="book">Book</option>
<option value="place">Place</option>
<option value="profile">Profile</option>
<option value="article">Article</option>
<option value="event">Event</option>
<option value="object">Object</option>
<option value="music.song">Music - Song</option>
<option value="music.radio_station">Music - Radio Station</option>
<option value="music.playlist">Music - Playlist</option>
<option value="music.album">Music - Album</option>
<option value="video.other">Video - Other</option>
<option value="video.tv_show">Video - TV Show</option>
<option value="video.movie">Video - Movies</option>
<option value="video.episode">Video - Episode</option>
<option value="books.author">Books - Author</option>
<option value="books.book">Books - Book</option>
<option value="books.genre">Books - Genre</option>
<option value="restaurant.restaurant">Restaurant</option>
<option value="restaurant.menu_item">Restaurant - Menu Item</option>
<option value="restaurant.menu_section">Restaurant - Menu Section</option>
<option value="restaurant.menu">Restaurant - Menu</option>
<option value="fitness.unit">Fitness - Unit</option>
<option value="fitness.course">Fitness - Course</option>