<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite9f77ce85b66af4341455f70cdb16bad
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'AdCaptcha\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'AdCaptcha\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'AdCaptcha\\Instantiate' => __DIR__ . '/../..' . '/src/Instantiate.php',
        'AdCaptcha\\Plugin\\AdCaptchaPlugin' => __DIR__ . '/../..' . '/src/Plugin/AdCaptchaPlugin.php',
        'AdCaptcha\\Plugin\\Comments' => __DIR__ . '/../..' . '/src/Plugin/Comments.php',
        'AdCaptcha\\Plugin\\ContactForm7\\Forms' => __DIR__ . '/../..' . '/src/Plugin/ContactForm7/Forms.php',
        'AdCaptcha\\Plugin\\Elementor\\Forms' => __DIR__ . '/../..' . '/src/Plugin/Elementor/Forms.php',
        'AdCaptcha\\Plugin\\FluentForms\\AdCaptchaElements' => __DIR__ . '/../..' . '/src/Plugin/FluentForms/AdCaptchaElements.php',
        'AdCaptcha\\Plugin\\FluentForms\\Forms' => __DIR__ . '/../..' . '/src/Plugin/FluentForms/Forms.php',
        'AdCaptcha\\Plugin\\Login' => __DIR__ . '/../..' . '/src/Plugin/Login.php',
        'AdCaptcha\\Plugin\\Mailchimp\\Forms' => __DIR__ . '/../..' . '/src/Plugin/Mailchimp/Forms.php',
        'AdCaptcha\\Plugin\\NinjaForms\\AdcaptchaField' => __DIR__ . '/../..' . '/src/Plugin/NinjaForms/AdcaptchaField.php',
        'AdCaptcha\\Plugin\\NinjaForms\\Forms' => __DIR__ . '/../..' . '/src/Plugin/NinjaForms/Forms.php',
        'AdCaptcha\\Plugin\\PasswordReset' => __DIR__ . '/../..' . '/src/Plugin/PasswordReset.php',
        'AdCaptcha\\Plugin\\Registration' => __DIR__ . '/../..' . '/src/Plugin/Registration.php',
        'AdCaptcha\\Plugin\\WPForms\\AdCAPTCHA_WPForms_Field' => __DIR__ . '/../..' . '/src/Plugin/WPForms/AdCAPTCHA_WPForms_Field.php',
        'AdCaptcha\\Plugin\\WPForms\\Forms' => __DIR__ . '/../..' . '/src/Plugin/WPForms/Forms.php',
        'AdCaptcha\\Plugin\\Woocommerce\\Checkout' => __DIR__ . '/../..' . '/src/Plugin/Woocommerce/Checkout.php',
        'AdCaptcha\\Plugin\\Woocommerce\\Login' => __DIR__ . '/../..' . '/src/Plugin/Woocommerce/Login.php',
        'AdCaptcha\\Plugin\\Woocommerce\\PasswordReset' => __DIR__ . '/../..' . '/src/Plugin/Woocommerce/PasswordReset.php',
        'AdCaptcha\\Plugin\\Woocommerce\\Registration' => __DIR__ . '/../..' . '/src/Plugin/Woocommerce/Registration.php',
        'AdCaptcha\\Settings\\Advanced' => __DIR__ . '/../..' . '/src/Settings/Advanced.php',
        'AdCaptcha\\Settings\\General' => __DIR__ . '/../..' . '/src/Settings/General.php',
        'AdCaptcha\\Settings\\Plugins' => __DIR__ . '/../..' . '/src/Settings/Plugins.php',
        'AdCaptcha\\Settings\\Settings' => __DIR__ . '/../..' . '/src/Settings/Settings.php',
        'AdCaptcha\\Widget\\AdCaptcha' => __DIR__ . '/../..' . '/src/Widget/AdCaptcha.php',
        'AdCaptcha\\Widget\\Verify' => __DIR__ . '/../..' . '/src/Widget/Verify.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite9f77ce85b66af4341455f70cdb16bad::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite9f77ce85b66af4341455f70cdb16bad::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite9f77ce85b66af4341455f70cdb16bad::$classMap;

        }, null, ClassLoader::class);
    }
}
