<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdminDebugTools\\Plugin\\Bootstrap\\Admin\\Pages' => $baseDir . '/includes/Bootstrap/Admin/Pages.php',
    'AdminDebugTools\\Plugin\\Container' => $baseDir . '/includes/Container.php',
    'AdminDebugTools\\Plugin\\Core\\FileContent' => $baseDir . '/includes/Core/FileContent.php',
    'AdminDebugTools\\Plugin\\Core\\FileContentGetter' => $baseDir . '/includes/Core/FileContentGetter.php',
    'AdminDebugTools\\Plugin\\Core\\FileContentLine' => $baseDir . '/includes/Core/FileContentLine.php',
    'AdminDebugTools\\Plugin\\Core\\LogLine' => $baseDir . '/includes/Core/LogLine.php',
    'AdminDebugTools\\Plugin\\Core\\LogLineCollection' => $baseDir . '/includes/Core/LogLineCollection.php',
    'AdminDebugTools\\Plugin\\Core\\LogParser' => $baseDir . '/includes/Core/LogParser.php',
    'AdminDebugTools\\Plugin\\Core\\SseServer' => $baseDir . '/includes/Core/SseServer.php',
    'AdminDebugTools\\Plugin\\Core\\WpLogParser' => $baseDir . '/includes/Core/WpLogParser.php',
    'AdminDebugTools\\Plugin\\Exceptions\\Container\\ContainerException' => $baseDir . '/includes/Exceptions/Container/ContainerException.php',
    'AdminDebugTools\\Plugin\\Exceptions\\Container\\NotFoundException' => $baseDir . '/includes/Exceptions/Container/NotFoundException.php',
    'AdminDebugTools\\Plugin\\Exceptions\\Exception' => $baseDir . '/includes/Exceptions/Exception.php',
    'AdminDebugTools\\Plugin\\Exceptions\\RestApi\\AuthorizationException' => $baseDir . '/includes/Exceptions/RestApi/AuthorizationException.php',
    'AdminDebugTools\\Plugin\\Exceptions\\RestApi\\InvalidParamException' => $baseDir . '/includes/Exceptions/RestApi/InvalidParamException.php',
    'AdminDebugTools\\Plugin\\Exceptions\\RestApi\\RestApiException' => $baseDir . '/includes/Exceptions/RestApi/RestApiException.php',
    'AdminDebugTools\\Plugin\\Exceptions\\UserFrienldlyException' => $baseDir . '/includes/Exceptions/UserFrienldlyException.php',
    'AdminDebugTools\\Plugin\\Options\\Options' => $baseDir . '/includes/Options/Options.php',
    'AdminDebugTools\\Plugin\\Plugin' => $baseDir . '/includes/Plugin.php',
    'AdminDebugTools\\Plugin\\RestApi\\Controllers\\BaseController' => $baseDir . '/includes/RestApi/Controllers/BaseController.php',
    'AdminDebugTools\\Plugin\\RestApi\\Controllers\\DebugLogController' => $baseDir . '/includes/RestApi/Controllers/DebugLogController.php',
    'AdminDebugTools\\Plugin\\RestApi\\Controllers\\WpConfigController' => $baseDir . '/includes/RestApi/Controllers/WpConfigController.php',
    'AdminDebugTools\\Plugin\\RestApi\\RestApi' => $baseDir . '/includes/RestApi/RestApi.php',
    'AdminDebugTools\\Plugin\\Utils\\Arr' => $baseDir . '/includes/Utils/Arr.php',
    'AdminDebugTools\\Plugin\\Utils\\Asset' => $baseDir . '/includes/Utils/Asset.php',
    'AdminDebugTools\\Plugin\\Utils\\Date' => $baseDir . '/includes/Utils/Date.php',
    'AdminDebugTools\\Plugin\\Utils\\Filesystem' => $baseDir . '/includes/Utils/Filesystem.php',
    'AdminDebugTools\\Plugin\\Utils\\Utils' => $baseDir . '/includes/Utils/Utils.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
