<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '7d88166f7223e12d726367cc1c928fca' => $vendorDir . '/ua1-labs/firebug/functions.php',
    '87e500a6ffd9d76e744f97d99e8ba8c3' => $vendorDir . '/ua1-labs/firesql/init.php',
);
