<?php

/**
 * MerchantPaymentApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BenefitPlusGatewaySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Benefit Plus e-commerce payment gateway 3
 *
 * This is a \"swagger\" definition of application programming interface of the Benefit Plus e-commerce payment gateway 3. You may leverage this API from your e-shop to integrate payments by employee-benefits-programme funds. This version of the programme uses mobile payment application Benefit Plus Pay. <br/><br/>RFC version - this is a conceptual document intended for reviewing by the Benefit Plus partnering merchants and for integration planning.</br></br> <b>Requests signing</b></br></br>All requests except <code>/auth/token</code> must be signed by \"SHA-256 with RSA\" (RSASSA-PKCS1-v1_5,  <a href=\"https://datatracker.ietf.org/doc/html/rfc8017#section-8.2\" target=\"_blank\" rel=\"noopener noreferrer\">RFC 8017 chapter 8.2</a>) electronic signatures. See online gateway documentation for details.
 *
 * The version of the OpenAPI document: 1.0.RFC8
 * Contact: partneri@benefit-plus.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace MuzaPayDeps\BenefitPlusGatewaySdk\Api;

use MuzaPayDeps\GuzzleHttp\Client;
use MuzaPayDeps\GuzzleHttp\ClientInterface;
use MuzaPayDeps\GuzzleHttp\Exception\ConnectException;
use MuzaPayDeps\GuzzleHttp\Exception\RequestException;
use MuzaPayDeps\GuzzleHttp\Psr7\MultipartStream;
use MuzaPayDeps\GuzzleHttp\Psr7\Request;
use MuzaPayDeps\GuzzleHttp\RequestOptions;
use MuzaPayDeps\BenefitPlusGatewaySdk\ApiException;
use MuzaPayDeps\BenefitPlusGatewaySdk\Configuration;
use MuzaPayDeps\BenefitPlusGatewaySdk\HeaderSelector;
use MuzaPayDeps\BenefitPlusGatewaySdk\ObjectSerializer;
/**
 * MerchantPaymentApi Class Doc Comment
 *
 * @category Class
 * @package  BenefitPlusGatewaySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MerchantPaymentApi
{
    /**
     * @var ClientInterface
     */
    protected $client;
    /**
     * @var Configuration
     */
    protected $config;
    /**
     * @var HeaderSelector
     */
    protected $headerSelector;
    /**
     * @var int Host index
     */
    protected $hostIndex;
    /** @var string[] $contentTypes **/
    public const contentTypes = ['cancelPayment' => ['application/json'], 'getPaymentState' => ['application/json'], 'initPayment' => ['application/json']];
    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }
    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }
    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }
    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }
    /**
     * Operation cancelPayment
     *
     * cancelPayment()
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelPayment'] to see the possible values for this operation
     *
     * @throws \BenefitPlusGatewaySdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function cancelPayment($payment_id, $signature, string $contentType = self::contentTypes['cancelPayment'][0])
    {
        $this->cancelPaymentWithHttpInfo($payment_id, $signature, $contentType);
    }
    /**
     * Operation cancelPaymentWithHttpInfo
     *
     * cancelPayment()
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelPayment'] to see the possible values for this operation
     *
     * @throws \BenefitPlusGatewaySdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelPaymentWithHttpInfo($payment_id, $signature, string $contentType = self::contentTypes['cancelPayment'][0])
    {
        $request = $this->cancelPaymentRequest($payment_id, $signature, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation cancelPaymentAsync
     *
     * cancelPayment()
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelPaymentAsync($payment_id, $signature, string $contentType = self::contentTypes['cancelPayment'][0])
    {
        return $this->cancelPaymentAsyncWithHttpInfo($payment_id, $signature, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation cancelPaymentAsyncWithHttpInfo
     *
     * cancelPayment()
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelPaymentAsyncWithHttpInfo($payment_id, $signature, string $contentType = self::contentTypes['cancelPayment'][0])
    {
        $returnType = '';
        $request = $this->cancelPaymentRequest($payment_id, $signature, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            return [null, $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'cancelPayment'
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cancelPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function cancelPaymentRequest($payment_id, $signature, string $contentType = self::contentTypes['cancelPayment'][0])
    {
        // verify the required parameter 'payment_id' is set
        if ($payment_id === null || is_array($payment_id) && count($payment_id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $payment_id when calling cancelPayment');
        }
        if (!preg_match("/^[A-F0-9]{32}\$/", $payment_id)) {
            throw new \InvalidArgumentException("invalid value for \"payment_id\" when calling MerchantPaymentApi.cancelPayment, must conform to the pattern /^[A-F0-9]{32}\$/.");
        }
        // verify the required parameter 'signature' is set
        if ($signature === null || is_array($signature) && count($signature) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $signature when calling cancelPayment');
        }
        $resourcePath = '/v1/payments/{paymentId}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $signature,
            'signature',
            // param base name
            'string',
            // openApiType
            'form',
            // style
            \true,
            // explode
            \true
        ) ?? []);
        // path params
        if ($payment_id !== null) {
            $resourcePath = str_replace('{' . 'paymentId' . '}', ObjectSerializer::toPathValue($payment_id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \MuzaPayDeps\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('PUT', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation getPaymentState
     *
     * getPaymentState()
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt;. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentState'] to see the possible values for this operation
     *
     * @throws \BenefitPlusGatewaySdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BenefitPlusGatewaySdk\Model\PaymentStateResponse|\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse
     */
    public function getPaymentState($payment_id, $signature, string $contentType = self::contentTypes['getPaymentState'][0])
    {
        list($response) = $this->getPaymentStateWithHttpInfo($payment_id, $signature, $contentType);
        return $response;
    }
    /**
     * Operation getPaymentStateWithHttpInfo
     *
     * getPaymentState()
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt;. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentState'] to see the possible values for this operation
     *
     * @throws \BenefitPlusGatewaySdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BenefitPlusGatewaySdk\Model\PaymentStateResponse|\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentStateWithHttpInfo($payment_id, $signature, string $contentType = self::contentTypes['getPaymentState'][0])
    {
        $request = $this->getPaymentStateRequest($payment_id, $signature, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\BenefitPlusGatewaySdk\Model\PaymentStateResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\PaymentStateResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\PaymentStateResponse', []), $response->getStatusCode(), $response->getHeaders()];
                case 400:
                    if ('\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse', []), $response->getStatusCode(), $response->getHeaders()];
                case 403:
                    if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', []), $response->getStatusCode(), $response->getHeaders()];
                case 404:
                    if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', []), $response->getStatusCode(), $response->getHeaders()];
                default:
                    if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\PaymentStateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\PaymentStateResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation getPaymentStateAsync
     *
     * getPaymentState()
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt;. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentState'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentStateAsync($payment_id, $signature, string $contentType = self::contentTypes['getPaymentState'][0])
    {
        return $this->getPaymentStateAsyncWithHttpInfo($payment_id, $signature, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation getPaymentStateAsyncWithHttpInfo
     *
     * getPaymentState()
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt;. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentState'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentStateAsyncWithHttpInfo($payment_id, $signature, string $contentType = self::contentTypes['getPaymentState'][0])
    {
        $returnType = 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\PaymentStateResponse';
        $request = $this->getPaymentStateRequest($payment_id, $signature, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'getPaymentState'
     *
     * @param  string $payment_id The unique identifier of the payment assigned by the gateway in /payments/init operation. (required)
     * @param  string $signature Request signature data. URL encoded. Sign &lt;b&gt;paymentId&lt;/b&gt;. See online gateway documentation for details. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPaymentState'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPaymentStateRequest($payment_id, $signature, string $contentType = self::contentTypes['getPaymentState'][0])
    {
        // verify the required parameter 'payment_id' is set
        if ($payment_id === null || is_array($payment_id) && count($payment_id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $payment_id when calling getPaymentState');
        }
        if (!preg_match("/^[A-F0-9]{32}\$/", $payment_id)) {
            throw new \InvalidArgumentException("invalid value for \"payment_id\" when calling MerchantPaymentApi.getPaymentState, must conform to the pattern /^[A-F0-9]{32}\$/.");
        }
        // verify the required parameter 'signature' is set
        if ($signature === null || is_array($signature) && count($signature) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $signature when calling getPaymentState');
        }
        $resourcePath = '/v1/payments/{paymentId}/state';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $signature,
            'signature',
            // param base name
            'string',
            // openApiType
            'form',
            // style
            \true,
            // explode
            \true
        ) ?? []);
        // path params
        if ($payment_id !== null) {
            $resourcePath = str_replace('{' . 'paymentId' . '}', ObjectSerializer::toPathValue($payment_id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \MuzaPayDeps\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation initPayment
     *
     * initPayment()
     *
     * @param  string $signature Request signature data. URL encoded. Sign X-Correlation-ID, &lt;b&gt;amount, productCode, orderReferenceCode&lt;/b&gt;, orderDescription, merchantData, &lt;b&gt;returnUrl, language&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  \BenefitPlusGatewaySdk\Model\InitPaymentRequest $init_payment_request init_payment_request (required)
     * @param  string $x_correlation_id Correlation identifier which may be sent by the e-shop in the request. The gateway will echo it in positive responses related to the same payment instance. Maximum length 128 characters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initPayment'] to see the possible values for this operation
     *
     * @throws \BenefitPlusGatewaySdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BenefitPlusGatewaySdk\Model\InitPaymentResponse|\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse
     */
    public function initPayment($signature, $init_payment_request, $x_correlation_id = null, string $contentType = self::contentTypes['initPayment'][0])
    {
        list($response) = $this->initPaymentWithHttpInfo($signature, $init_payment_request, $x_correlation_id, $contentType);
        return $response;
    }
    /**
     * Operation initPaymentWithHttpInfo
     *
     * initPayment()
     *
     * @param  string $signature Request signature data. URL encoded. Sign X-Correlation-ID, &lt;b&gt;amount, productCode, orderReferenceCode&lt;/b&gt;, orderDescription, merchantData, &lt;b&gt;returnUrl, language&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  \BenefitPlusGatewaySdk\Model\InitPaymentRequest $init_payment_request (required)
     * @param  string $x_correlation_id Correlation identifier which may be sent by the e-shop in the request. The gateway will echo it in positive responses related to the same payment instance. Maximum length 128 characters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initPayment'] to see the possible values for this operation
     *
     * @throws \BenefitPlusGatewaySdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BenefitPlusGatewaySdk\Model\InitPaymentResponse|\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse|\BenefitPlusGatewaySdk\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function initPaymentWithHttpInfo($signature, $init_payment_request, $x_correlation_id = null, string $contentType = self::contentTypes['initPayment'][0])
    {
        $request = $this->initPaymentRequest($signature, $init_payment_request, $x_correlation_id, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('\BenefitPlusGatewaySdk\Model\InitPaymentResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\InitPaymentResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\InitPaymentResponse', []), $response->getStatusCode(), $response->getHeaders()];
                case 400:
                    if ('\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse', []), $response->getStatusCode(), $response->getHeaders()];
                case 403:
                    if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', []), $response->getStatusCode(), $response->getHeaders()];
                default:
                    if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BenefitPlusGatewaySdk\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\InitPaymentResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\InitPaymentResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\BadRequestErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation initPaymentAsync
     *
     * initPayment()
     *
     * @param  string $signature Request signature data. URL encoded. Sign X-Correlation-ID, &lt;b&gt;amount, productCode, orderReferenceCode&lt;/b&gt;, orderDescription, merchantData, &lt;b&gt;returnUrl, language&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  \BenefitPlusGatewaySdk\Model\InitPaymentRequest $init_payment_request (required)
     * @param  string $x_correlation_id Correlation identifier which may be sent by the e-shop in the request. The gateway will echo it in positive responses related to the same payment instance. Maximum length 128 characters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function initPaymentAsync($signature, $init_payment_request, $x_correlation_id = null, string $contentType = self::contentTypes['initPayment'][0])
    {
        return $this->initPaymentAsyncWithHttpInfo($signature, $init_payment_request, $x_correlation_id, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation initPaymentAsyncWithHttpInfo
     *
     * initPayment()
     *
     * @param  string $signature Request signature data. URL encoded. Sign X-Correlation-ID, &lt;b&gt;amount, productCode, orderReferenceCode&lt;/b&gt;, orderDescription, merchantData, &lt;b&gt;returnUrl, language&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  \BenefitPlusGatewaySdk\Model\InitPaymentRequest $init_payment_request (required)
     * @param  string $x_correlation_id Correlation identifier which may be sent by the e-shop in the request. The gateway will echo it in positive responses related to the same payment instance. Maximum length 128 characters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function initPaymentAsyncWithHttpInfo($signature, $init_payment_request, $x_correlation_id = null, string $contentType = self::contentTypes['initPayment'][0])
    {
        $returnType = 'MuzaPayDeps\BenefitPlusGatewaySdk\Model\InitPaymentResponse';
        $request = $this->initPaymentRequest($signature, $init_payment_request, $x_correlation_id, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'initPayment'
     *
     * @param  string $signature Request signature data. URL encoded. Sign X-Correlation-ID, &lt;b&gt;amount, productCode, orderReferenceCode&lt;/b&gt;, orderDescription, merchantData, &lt;b&gt;returnUrl, language&lt;/b&gt; in this order. See online gateway documentation for details. (required)
     * @param  \BenefitPlusGatewaySdk\Model\InitPaymentRequest $init_payment_request (required)
     * @param  string $x_correlation_id Correlation identifier which may be sent by the e-shop in the request. The gateway will echo it in positive responses related to the same payment instance. Maximum length 128 characters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['initPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function initPaymentRequest($signature, $init_payment_request, $x_correlation_id = null, string $contentType = self::contentTypes['initPayment'][0])
    {
        // verify the required parameter 'signature' is set
        if ($signature === null || is_array($signature) && count($signature) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $signature when calling initPayment');
        }
        // verify the required parameter 'init_payment_request' is set
        if ($init_payment_request === null || is_array($init_payment_request) && count($init_payment_request) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $init_payment_request when calling initPayment');
        }
        if ($x_correlation_id !== null && !preg_match("/^[ -~]{0,128}\$/", $x_correlation_id)) {
            throw new \InvalidArgumentException("invalid value for \"x_correlation_id\" when calling MerchantPaymentApi.initPayment, must conform to the pattern /^[ -~]{0,128}\$/.");
        }
        $resourcePath = '/v1/payments/init';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $signature,
            'signature',
            // param base name
            'string',
            // openApiType
            'form',
            // style
            \true,
            // explode
            \true
        ) ?? []);
        // header params
        if ($x_correlation_id !== null) {
            $headerParams['X-Correlation-ID'] = ObjectSerializer::toHeaderValue($x_correlation_id);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($init_payment_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \MuzaPayDeps\GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($init_payment_request));
            } else {
                $httpBody = $init_payment_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \MuzaPayDeps\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('POST', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }
        return $options;
    }
}
