<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit83a9cbe6c2bf98ff5f4dda25ad1375f4
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'ByteKit\\' => 8,
        ),
        'A' => 
        array (
            'AutocompleteOrdersForWooCommerce\\' => 33,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ByteKit\\' => 
        array (
            0 => __DIR__ . '/..' . '/byteever/bytekit-plugin/src',
        ),
        'AutocompleteOrdersForWooCommerce\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'AutocompleteOrdersForWooCommerce\\Admin\\Admin' => __DIR__ . '/../..' . '/includes/Admin/Admin.php',
        'AutocompleteOrdersForWooCommerce\\Admin\\Notices' => __DIR__ . '/../..' . '/includes/Admin/Notices.php',
        'AutocompleteOrdersForWooCommerce\\Orders' => __DIR__ . '/../..' . '/includes/Orders.php',
        'AutocompleteOrdersForWooCommerce\\Plugin' => __DIR__ . '/../..' . '/includes/Plugin.php',
        'ByteKit\\Admin\\Flash' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Flash.php',
        'ByteKit\\Admin\\Notices' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Notices.php',
        'ByteKit\\Interfaces\\Pluginable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
        'ByteKit\\Interfaces\\Scriptable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
        'ByteKit\\Plugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Plugin.php',
        'ByteKit\\Scripts' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Scripts.php',
        'ByteKit\\Services' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Services.php',
        'ByteKit\\Traits\\HasPlugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit83a9cbe6c2bf98ff5f4dda25ad1375f4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit83a9cbe6c2bf98ff5f4dda25ad1375f4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit83a9cbe6c2bf98ff5f4dda25ad1375f4::$classMap;

        }, null, ClassLoader::class);
    }
}
