<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'TagConcierge\\ConsentModeBannerFree\\' => array($baseDir . '/src'),
);
