<?php
function ambikly_currencies()
{
    static $currencies;

    if (!isset($currencies)) {
        $currencies = array_unique(
            apply_filters(
                'ambikly_currencies',
                array(
                    'AED' => esc_html__('United Arab Emirates dirham', 'ambikly'),
                    'AFN' => esc_html__('Afghan afghani', 'ambikly'),
                    'ALL' => esc_html__('Albanian lek', 'ambikly'),
                    'AMD' => esc_html__('Armenian dram', 'ambikly'),
                    'ANG' => esc_html__('Netherlands Antillean guilder', 'ambikly'),
                    'AOA' => esc_html__('Angolan kwanza', 'ambikly'),
                    'ARS' => esc_html__('Argentine peso', 'ambikly'),
                    'AUD' => esc_html__('Australian dollar', 'ambikly'),
                    'AWG' => esc_html__('Aruban florin', 'ambikly'),
                    'AZN' => esc_html__('Azerbaijani manat', 'ambikly'),
                    'BAM' => esc_html__('Bosnia and Herzegovina convertible mark', 'ambikly'),
                    'BBD' => esc_html__('Barbadian dollar', 'ambikly'),
                    'BDT' => esc_html__('Bangladeshi taka', 'ambikly'),
                    'BGN' => esc_html__('Bulgarian lev', 'ambikly'),
                    'BHD' => esc_html__('Bahraini dinar', 'ambikly'),
                    'BIF' => esc_html__('Burundian franc', 'ambikly'),
                    'BMD' => esc_html__('Bermudian dollar', 'ambikly'),
                    'BND' => esc_html__('Brunei dollar', 'ambikly'),
                    'BOB' => esc_html__('Bolivian boliviano', 'ambikly'),
                    'BRL' => esc_html__('Brazilian real', 'ambikly'),
                    'BSD' => esc_html__('Bahamian dollar', 'ambikly'),
                    'BTC' => esc_html__('Bitcoin', 'ambikly'),
                    'BTN' => esc_html__('Bhutanese ngultrum', 'ambikly'),
                    'BWP' => esc_html__('Botswana pula', 'ambikly'),
                    'BYR' => esc_html__('Belarusian ruble (old)', 'ambikly'),
                    'BYN' => esc_html__('Belarusian ruble', 'ambikly'),
                    'BZD' => esc_html__('Belize dollar', 'ambikly'),
                    'CAD' => esc_html__('Canadian dollar', 'ambikly'),
                    'CDF' => esc_html__('Congolese franc', 'ambikly'),
                    'CHF' => esc_html__('Swiss franc', 'ambikly'),
                    'CLP' => esc_html__('Chilean peso', 'ambikly'),
                    'CNY' => esc_html__('Chinese yuan', 'ambikly'),
                    'COP' => esc_html__('Colombian peso', 'ambikly'),
                    'CRC' => esc_html__('Costa Rican col&oacute;n', 'ambikly'),
                    'CUC' => esc_html__('Cuban convertible peso', 'ambikly'),
                    'CUP' => esc_html__('Cuban peso', 'ambikly'),
                    'CVE' => esc_html__('Cape Verdean escudo', 'ambikly'),
                    'CZK' => esc_html__('Czech koruna', 'ambikly'),
                    'DJF' => esc_html__('Djiboutian franc', 'ambikly'),
                    'DKK' => esc_html__('Danish krone', 'ambikly'),
                    'DOP' => esc_html__('Dominican peso', 'ambikly'),
                    'DZD' => esc_html__('Algerian dinar', 'ambikly'),
                    'EGP' => esc_html__('Egyptian pound', 'ambikly'),
                    'ERN' => esc_html__('Eritrean nakfa', 'ambikly'),
                    'ETB' => esc_html__('Ethiopian birr', 'ambikly'),
                    'EUR' => esc_html__('Euro', 'ambikly'),
                    'FJD' => esc_html__('Fijian dollar', 'ambikly'),
                    'FKP' => esc_html__('Falkland Islands pound', 'ambikly'),
                    'GBP' => esc_html__('Pound sterling', 'ambikly'),
                    'GEL' => esc_html__('Georgian lari', 'ambikly'),
                    'GGP' => esc_html__('Guernsey pound', 'ambikly'),
                    'GHS' => esc_html__('Ghana cedi', 'ambikly'),
                    'GIP' => esc_html__('Gibraltar pound', 'ambikly'),
                    'GMD' => esc_html__('Gambian dalasi', 'ambikly'),
                    'GNF' => esc_html__('Guinean franc', 'ambikly'),
                    'GTQ' => esc_html__('Guatemalan quetzal', 'ambikly'),
                    'GYD' => esc_html__('Guyanese dollar', 'ambikly'),
                    'HKD' => esc_html__('Hong Kong dollar', 'ambikly'),
                    'HNL' => esc_html__('Honduran lempira', 'ambikly'),
                    'HRK' => esc_html__('Croatian kuna', 'ambikly'),
                    'HTG' => esc_html__('Haitian gourde', 'ambikly'),
                    'HUF' => esc_html__('Hungarian forint', 'ambikly'),
                    'IDR' => esc_html__('Indonesian rupiah', 'ambikly'),
                    'ILS' => esc_html__('Israeli new shekel', 'ambikly'),
                    'IMP' => esc_html__('Manx pound', 'ambikly'),
                    'INR' => esc_html__('Indian rupee', 'ambikly'),
                    'IQD' => esc_html__('Iraqi dinar', 'ambikly'),
                    'IRR' => esc_html__('Iranian rial', 'ambikly'),
                    'IRT' => esc_html__('Iranian toman', 'ambikly'),
                    'ISK' => esc_html__('Icelandic kr&oacute;na', 'ambikly'),
                    'JEP' => esc_html__('Jersey pound', 'ambikly'),
                    'JMD' => esc_html__('Jamaican dollar', 'ambikly'),
                    'JOD' => esc_html__('Jordanian dinar', 'ambikly'),
                    'JPY' => esc_html__('Japanese yen', 'ambikly'),
                    'KES' => esc_html__('Kenyan shilling', 'ambikly'),
                    'KGS' => esc_html__('Kyrgyzstani som', 'ambikly'),
                    'KHR' => esc_html__('Cambodian riel', 'ambikly'),
                    'KMF' => esc_html__('Comorian franc', 'ambikly'),
                    'KPW' => esc_html__('North Korean won', 'ambikly'),
                    'KRW' => esc_html__('South Korean won', 'ambikly'),
                    'KWD' => esc_html__('Kuwaiti dinar', 'ambikly'),
                    'KYD' => esc_html__('Cayman Islands dollar', 'ambikly'),
                    'KZT' => esc_html__('Kazakhstani tenge', 'ambikly'),
                    'LAK' => esc_html__('Lao kip', 'ambikly'),
                    'LBP' => esc_html__('Lebanese pound', 'ambikly'),
                    'LKR' => esc_html__('Sri Lankan rupee', 'ambikly'),
                    'LRD' => esc_html__('Liberian dollar', 'ambikly'),
                    'LSL' => esc_html__('Lesotho loti', 'ambikly'),
                    'LYD' => esc_html__('Libyan dinar', 'ambikly'),
                    'MAD' => esc_html__('Moroccan dirham', 'ambikly'),
                    'MDL' => esc_html__('Moldovan leu', 'ambikly'),
                    'MGA' => esc_html__('Malagasy ariary', 'ambikly'),
                    'MKD' => esc_html__('Macedonian denar', 'ambikly'),
                    'MMK' => esc_html__('Burmese kyat', 'ambikly'),
                    'MNT' => esc_html__('Mongolian t&ouml;gr&ouml;g', 'ambikly'),
                    'MOP' => esc_html__('Macanese pataca', 'ambikly'),
                    'MRU' => esc_html__('Mauritanian ouguiya', 'ambikly'),
                    'MUR' => esc_html__('Mauritian rupee', 'ambikly'),
                    'MVR' => esc_html__('Maldivian rufiyaa', 'ambikly'),
                    'MWK' => esc_html__('Malawian kwacha', 'ambikly'),
                    'MXN' => esc_html__('Mexican peso', 'ambikly'),
                    'MYR' => esc_html__('Malaysian ringgit', 'ambikly'),
                    'MZN' => esc_html__('Mozambican metical', 'ambikly'),
                    'NAD' => esc_html__('Namibian dollar', 'ambikly'),
                    'NGN' => esc_html__('Nigerian naira', 'ambikly'),
                    'NIO' => esc_html__('Nicaraguan c&oacute;rdoba', 'ambikly'),
                    'NOK' => esc_html__('Norwegian krone', 'ambikly'),
                    'NPR' => esc_html__('Nepalese rupee', 'ambikly'),
                    'NZD' => esc_html__('New Zealand dollar', 'ambikly'),
                    'OMR' => esc_html__('Omani rial', 'ambikly'),
                    'PAB' => esc_html__('Panamanian balboa', 'ambikly'),
                    'PEN' => esc_html__('Sol', 'ambikly'),
                    'PGK' => esc_html__('Papua New Guinean kina', 'ambikly'),
                    'PHP' => esc_html__('Philippine peso', 'ambikly'),
                    'PKR' => esc_html__('Pakistani rupee', 'ambikly'),
                    'PLN' => esc_html__('Polish z&#x142;oty', 'ambikly'),
                    'PRB' => esc_html__('Transnistrian ruble', 'ambikly'),
                    'PYG' => esc_html__('Paraguayan guaran&iacute;', 'ambikly'),
                    'QAR' => esc_html__('Qatari riyal', 'ambikly'),
                    'RON' => esc_html__('Romanian leu', 'ambikly'),
                    'RSD' => esc_html__('Serbian dinar', 'ambikly'),
                    'RUB' => esc_html__('Russian ruble', 'ambikly'),
                    'RWF' => esc_html__('Rwandan franc', 'ambikly'),
                    'SAR' => esc_html__('Saudi riyal', 'ambikly'),
                    'SBD' => esc_html__('Solomon Islands dollar', 'ambikly'),
                    'SCR' => esc_html__('Seychellois rupee', 'ambikly'),
                    'SDG' => esc_html__('Sudanese pound', 'ambikly'),
                    'SEK' => esc_html__('Swedish krona', 'ambikly'),
                    'SGD' => esc_html__('Singapore dollar', 'ambikly'),
                    'SHP' => esc_html__('Saint Helena pound', 'ambikly'),
                    'SLL' => esc_html__('Sierra Leonean leone', 'ambikly'),
                    'SOS' => esc_html__('Somali shilling', 'ambikly'),
                    'SRD' => esc_html__('Surinamese dollar', 'ambikly'),
                    'SSP' => esc_html__('South Sudanese pound', 'ambikly'),
                    'STN' => esc_html__('S&atilde;o Tom&eacute; and Pr&iacute;ncipe dobra', 'ambikly'),
                    'SYP' => esc_html__('Syrian pound', 'ambikly'),
                    'SZL' => esc_html__('Swazi lilangeni', 'ambikly'),
                    'THB' => esc_html__('Thai baht', 'ambikly'),
                    'TJS' => esc_html__('Tajikistani somoni', 'ambikly'),
                    'TMT' => esc_html__('Turkmenistan manat', 'ambikly'),
                    'TND' => esc_html__('Tunisian dinar', 'ambikly'),
                    'TOP' => esc_html__('Tongan pa&#x2bb;anga', 'ambikly'),
                    'TRY' => esc_html__('Turkish lira', 'ambikly'),
                    'TTD' => esc_html__('Trinidad and Tobago dollar', 'ambikly'),
                    'TWD' => esc_html__('New Taiwan dollar', 'ambikly'),
                    'TZS' => esc_html__('Tanzanian shilling', 'ambikly'),
                    'UAH' => esc_html__('Ukrainian hryvnia', 'ambikly'),
                    'UGX' => esc_html__('Ugandan shilling', 'ambikly'),
                    'USD' => esc_html__('United States (US) dollar', 'ambikly'),
                    'UYU' => esc_html__('Uruguayan peso', 'ambikly'),
                    'UZS' => esc_html__('Uzbekistani som', 'ambikly'),
                    'VEF' => esc_html__('Venezuelan bol&iacute;var (2008–2018)', 'ambikly'),
                    'VES' => esc_html__('Venezuelan bol&iacute;var', 'ambikly'),
                    'VND' => esc_html__('Vietnamese &#x111;&#x1ed3;ng', 'ambikly'),
                    'VUV' => esc_html__('Vanuatu vatu', 'ambikly'),
                    'WST' => esc_html__('Samoan t&#x101;l&#x101;', 'ambikly'),
                    'XAF' => esc_html__('Central African CFA franc', 'ambikly'),
                    'XCD' => esc_html__('East Caribbean dollar', 'ambikly'),
                    'XOF' => esc_html__('West African CFA franc', 'ambikly'),
                    'XPF' => esc_html__('CFP franc', 'ambikly'),
                    'YER' => esc_html__('Yemeni rial', 'ambikly'),
                    'ZAR' => esc_html__('South African rand', 'ambikly'),
                    'ZMW' => esc_html__('Zambian kwacha', 'ambikly'),
                )
            )
        );
    }

    return $currencies;
}

function ambikly_currency_symbols()
{

    $symbols = apply_filters(
        'ambikly_currency_symbols',
        array(
            'AED' => '&#x62f;.&#x625;',
            'AFN' => '&#x60b;',
            'ALL' => 'L',
            'AMD' => 'AMD',
            'ANG' => '&fnof;',
            'AOA' => 'Kz',
            'ARS' => '&#36;',
            'AUD' => '&#36;',
            'AWG' => 'Afl.',
            'AZN' => '&#8380;',
            'BAM' => 'KM',
            'BBD' => '&#36;',
            'BDT' => '&#2547;&nbsp;',
            'BGN' => '&#1083;&#1074;.',
            'BHD' => '.&#x62f;.&#x628;',
            'BIF' => 'Fr',
            'BMD' => '&#36;',
            'BND' => '&#36;',
            'BOB' => 'Bs.',
            'BRL' => '&#82;&#36;',
            'BSD' => '&#36;',
            'BTC' => '&#3647;',
            'BTN' => 'Nu.',
            'BWP' => 'P',
            'BYR' => 'Br',
            'BYN' => 'Br',
            'BZD' => '&#36;',
            'CAD' => '&#36;',
            'CDF' => 'Fr',
            'CHF' => '&#67;&#72;&#70;',
            'CLP' => '&#36;',
            'CNY' => '&yen;',
            'COP' => '&#36;',
            'CRC' => '&#x20a1;',
            'CUC' => '&#36;',
            'CUP' => '&#36;',
            'CVE' => '&#36;',
            'CZK' => '&#75;&#269;',
            'DJF' => 'Fr',
            'DKK' => 'kr.',
            'DOP' => 'RD&#36;',
            'DZD' => '&#x62f;.&#x62c;',
            'EGP' => 'EGP',
            'ERN' => 'Nfk',
            'ETB' => 'Br',
            'EUR' => '&euro;',
            'FJD' => '&#36;',
            'FKP' => '&pound;',
            'GBP' => '&pound;',
            'GEL' => '&#x20be;',
            'GGP' => '&pound;',
            'GHS' => '&#x20b5;',
            'GIP' => '&pound;',
            'GMD' => 'D',
            'GNF' => 'Fr',
            'GTQ' => 'Q',
            'GYD' => '&#36;',
            'HKD' => '&#36;',
            'HNL' => 'L',
            'HRK' => 'kn',
            'HTG' => 'G',
            'HUF' => '&#70;&#116;',
            'IDR' => 'Rp',
            'ILS' => '&#8362;',
            'IMP' => '&pound;',
            'INR' => '&#8377;',
            'IQD' => '&#x62f;.&#x639;',
            'IRR' => '&#xfdfc;',
            'IRT' => '&#x062A;&#x0648;&#x0645;&#x0627;&#x0646;',
            'ISK' => 'kr.',
            'JEP' => '&pound;',
            'JMD' => '&#36;',
            'JOD' => '&#x62f;.&#x627;',
            'JPY' => '&yen;',
            'KES' => 'KSh',
            'KGS' => '&#x441;&#x43e;&#x43c;',
            'KHR' => '&#x17db;',
            'KMF' => 'Fr',
            'KPW' => '&#x20a9;',
            'KRW' => '&#8361;',
            'KWD' => '&#x62f;.&#x643;',
            'KYD' => '&#36;',
            'KZT' => '&#8376;',
            'LAK' => '&#8365;',
            'LBP' => '&#x644;.&#x644;',
            'LKR' => '&#xdbb;&#xdd4;',
            'LRD' => '&#36;',
            'LSL' => 'L',
            'LYD' => '&#x62f;.&#x644;',
            'MAD' => '&#x62f;.&#x645;.',
            'MDL' => 'MDL',
            'MGA' => 'Ar',
            'MKD' => '&#x434;&#x435;&#x43d;',
            'MMK' => 'Ks',
            'MNT' => '&#x20ae;',
            'MOP' => 'P',
            'MRU' => 'UM',
            'MUR' => '&#x20a8;',
            'MVR' => '.&#x783;',
            'MWK' => 'MK',
            'MXN' => '&#36;',
            'MYR' => '&#82;&#77;',
            'MZN' => 'MT',
            'NAD' => 'N&#36;',
            'NGN' => '&#8358;',
            'NIO' => 'C&#36;',
            'NOK' => '&#107;&#114;',
            'NPR' => '&#8360;',
            'NZD' => '&#36;',
            'OMR' => '&#x631;.&#x639;.',
            'PAB' => 'B/.',
            'PEN' => 'S/',
            'PGK' => 'K',
            'PHP' => '&#8369;',
            'PKR' => '&#8360;',
            'PLN' => '&#122;&#322;',
            'PRB' => '&#x440;.',
            'PYG' => '&#8370;',
            'QAR' => '&#x631;.&#x642;',
            'RMB' => '&yen;',
            'RON' => 'lei',
            'RSD' => '&#1088;&#1089;&#1076;',
            'RUB' => '&#8381;',
            'RWF' => 'Fr',
            'SAR' => '&#x631;.&#x633;',
            'SBD' => '&#36;',
            'SCR' => '&#x20a8;',
            'SDG' => '&#x62c;.&#x633;.',
            'SEK' => '&#107;&#114;',
            'SGD' => '&#36;',
            'SHP' => '&pound;',
            'SLL' => 'Le',
            'SOS' => 'Sh',
            'SRD' => '&#36;',
            'SSP' => '&pound;',
            'STN' => 'Db',
            'SYP' => '&#x644;.&#x633;',
            'SZL' => 'E',
            'THB' => '&#3647;',
            'TJS' => '&#x405;&#x41c;',
            'TMT' => 'm',
            'TND' => '&#x62f;.&#x62a;',
            'TOP' => 'T&#36;',
            'TRY' => '&#8378;',
            'TTD' => '&#36;',
            'TWD' => '&#78;&#84;&#36;',
            'TZS' => 'Sh',
            'UAH' => '&#8372;',
            'UGX' => 'UGX',
            'USD' => '&#36;',
            'UYU' => '&#36;',
            'UZS' => 'UZS',
            'VEF' => 'Bs F',
            'VES' => 'Bs.',
            'VND' => '&#8363;',
            'VUV' => 'Vt',
            'WST' => 'T',
            'XAF' => 'CFA',
            'XCD' => '&#36;',
            'XOF' => 'CFA',
            'XPF' => 'XPF',
            'YER' => '&#xfdfc;',
            'ZAR' => '&#82;',
            'ZMW' => 'ZK',
        )
    );

    return $symbols;
}

function ambikly_currency_symbol($currency = '')
{
    if (!$currency) {
        $currency = ambikly_currency();
    }

    $symbols = ambikly_currency_symbols();

    $currency_symbol = $symbols[$currency] ?? '';

    return apply_filters('ambikly_currency_symbol', $currency_symbol, $currency);
}

function ambikly_currency()
{
    return ambikly_get_option('currency', 'USD');
}
