<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'GenieImageAi\\Bootstrap\\' => array($baseDir . '/bootstrap'),
    'GenieImageAi\\App\\' => array($baseDir . '/app'),
);
