<?php

return [
    'id' => 'Ид',
    'classifier' => 'Классификатор',
    'classifier_id' => 'ИдКлассификатора',
    'name' => 'Наименование',
    'description' => 'Описание',
    'image' => 'Картинка',
    'weight' => 'Вес',
    'sku' => 'Артикул',
    'width' => 'Ширина',
    'length' => 'Длина',
    'height' => 'Высота',
    'properties' => 'Свойства',
    'property' => 'Свойство',
    'property_value' => 'ЗначенияСвойств',
    'variant_values' => 'ВариантыЗначений',
    'xml_value' => 'Значение',
    'multi' => 'Множественное',
    'categories' => 'Группы',
    'category' => 'Группа',
    'catalog' => 'Каталог',
    'products' => 'Товары',
    'product' => 'Товар',
    'starter' => '<?xml version="1.0" encoding="UTF-8"?><КоммерческаяИнформация xmlns="urn:1C.ru:commerceml_2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ВерсияСхемы=":version" ДатаФормирования=":date"></КоммерческаяИнформация>',
    'offersPackage' => 'ПакетПредложений',
    'offers' => 'Предложения',
    'offer' => 'Предложение',
];