<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0249bdde788973a1c6666af563d5456c
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DistinctiveLightbox\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DistinctiveLightbox\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes/classes',
        ),
    );

    public static $classMap = array (
        'DistinctiveLightbox\\Admin\\SettingsPage' => __DIR__ . '/../..' . '/includes/classes/Admin/SettingsPage.php',
        'DistinctiveLightbox\\DistinctiveLightbox' => __DIR__ . '/../..' . '/includes/classes/DistinctiveLightbox.php',
        'DistinctiveLightbox\\ImageHandling\\ImageHandling' => __DIR__ . '/../..' . '/includes/classes/ImageHandling/ImageHandling.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0249bdde788973a1c6666af563d5456c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0249bdde788973a1c6666af563d5456c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0249bdde788973a1c6666af563d5456c::$classMap;

        }, null, ClassLoader::class);
    }
}
