<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'MatterWP\\WPSubscriptionManager\\' => array($vendorDir . '/matterwp/wp-subscription-manager/src'),
    'Alter\\Core\\' => array($baseDir . '/src/Core/Controllers'),
    'Alter\\Admin\\' => array($baseDir . '/src/Admin/Controllers'),
);
