var amem;
(function(g){"undefined"===typeof acf?console.error("acf-input.js not found. AMem requires ACF to work."):(amem={forms:{},setup_form:function(a){var b=a.attr("data-key"),c={$el:a,key:b,submissionSteps:[]};this.pages.initialize(c);this.ajax.initialize(c);this.forms[b]=c;var e=this;c.$el.on("submit",function(d){d.preventDefault();amem.lock(c);(d=c.$el.data("acf"))&&d.set("status","");acf.validation.fetch({form:c.$el,failure:function(){amem.unlock(c)},success:function(){var f=c.submissionSteps.slice();e.executeSubmissionSteps(c,
f)},complete:function(){c.$el.find(".amem-submit-button").prop("disabled",!1)}})});acf.doAction("amem/form/setup",c)},lock(a){a.$el.find(".amem-submit-button").prop("disabled",!0);acf.validation.lockForm(a.$el)},unlock(a){a.$el.find(".amem-submit-button").prop("disabled",!1);acf.validation.unlockForm(a.$el)},addSubmissionStep(a,b,c){c={priority:b,fn:c};for(var e=0;e<a.submissionSteps.length;e++)if(b<a.submissionSteps[e].priority){a.submissionSteps.splice(e,0,c);return}a.submissionSteps.push(c)},executeSubmissionSteps(a,
b){var c=function(){amem.lock(a);a.$el.get(0).submit()};if(0==b.length)c();else{var e=this;b.shift().fn(0==b.length?c:function(){e.executeSubmissionSteps(a,b)})}},pages:{initialize:function(a){var b=this;$page_fields=a.$el.find(".acf-field-page");if($page_fields.exists()){a.pages=[];a.current_page=0;a.max_page=0;a.show_numbering=!0;a.$page_wrap=g('<div class="amem-page-wrap">');a.$page_wrap.insertBefore($page_fields.first());a.$previous_button=$page_fields.first().find(".amem-previous-button");a.$next_button=
$page_fields.first().find(".amem-next-button");a.show_numbering="true"===$page_fields.first().find(".amem-page-button").attr("data-show-numbering");a.$previous_button.click(function(d){d.preventDefault();b.previousPage(a)});a.$next_button.click(function(d){d.preventDefault();b.nextPage(a)});var c=a.$el.find(".amem-submit");c.prepend(a.$next_button);c.prepend(a.$previous_button);a.$submit_button=c.find(".amem-submit-button");var e=0;$page_fields.each(function(d,f){d=g(f);var k=e;f=d.nextUntil(".acf-field-page",
".acf-field");if(0!=f.length){var h=d.find(".amem-page-button").attr("data-index",k);h.click(function(l){l.preventDefault();amem.pages.navigateToPage(k,a)});a.show_numbering&&($index=g('<span class="index">').html(k+1),h.prepend($index));a.$page_wrap.append(h);a.pages.push({$field:d,$fields:f,$button:h});e++}});this.refresh(a)}},refresh:function(a){g.each(a.pages,function(e,d){var f=e==a.current_page;d.$button.toggleClass("enabled",e<=a.max_page);d.$button.toggleClass("current",f);d.$fields.each(function(){g(this).toggle(f)})});
var b=this.isFirstPage(a),c=this.isLastPage(a);a.$previous_button.attr("disabled",b?!0:null);a.$next_button.toggle(!c);a.$submit_button.toggle(c)},nextPage:function(a){if(!this.isLastPage(a)){var b=this;this.validatePage(a,a.current_page,function(){b.changePage(a.current_page+1,a)})}},previousPage:function(a){this.isFirstPage(a)||this.changePage(a.current_page-1,a)},navigateToPage:function(a,b){if(!(0>a||a>b.max_page)){var c=this;this.validatePage(b,b.current_page,function(){c.changePage(a,b)})}},
changePage:function(a,b){var c=b.current_page;b.current_page=a;b.max_page<=b.current_page&&(b.max_page=b.current_page);this.refresh(b);acf.doAction("amem/form/page_changed",a,c,b)},isFirstPage:function(a){return 0==a.current_page},isLastPage:function(a){return a.current_page==a.pages.length-1},validatePage:function(a,b,c){a.pages[b].$fields.find("input").each(function(){this.checkValidity()});var e=function(f){for(i=0;i<a.pages.length;i++)i!=b&&f(a.pages[i])};e(function(f){f.$fields.detach()});var d=
function(){e(function(f){f.$fields.insertAfter(f.$field)})};acf.validation.fetch({form:a.$el,lock:!1,reset:!0,success:function(){d();c()},failure:function(){d()}})}},ajax:{initialize:function(a){var b=this;a.$el.is("[data-ajax]")&&amem.addSubmissionStep(a,100,function(c){b.sendSubmission(a)})},sendSubmission:function(a){var b=new FormData(a.$el.get(0));b.append("action","amem_submission");g.ajax({url:acf.get("ajaxurl"),data:b,processData:!1,contentType:!1,type:"post",success:this.onSuccess(a),error:this.onError(a),
complete:function(){amem.unlock(a)}})},onSuccess:function(a){return function(b){b=b.data;acf.doAction("amem/form/ajax/submission",b,a);switch(b.type){case "success_message":b=g(b.success_message);a.$el.find(".amem-success-message, .amem-error-message, .amem-updated-message").remove();a.$el.find('input[name="acf[user_password]"], input[name="acf[user_password_confirm]"], input[name="acf[user_password_current]"], input[name="user_password"], input[name="user_password_confirm"]').val("");a.$el.find(".pass-strength-result, .pass-strength-result").html("");
a.$el.prepend(b);break;case "just_success_message":b=g(b.success_message);a.$el.find(".amem-fields").replaceWith(b);break;case "redirect":window.location.href=b.redirect_url}}},onError:function(a){return function(b){var c=a.$el.data("acf");c.addErrors(b.responseJSON.data.errors);c.showErrors()}}}},g(document).ready(function(){g(".amem-form").each(function(){amem.setup_form(g(this))})}))})(jQuery);
