<?php return array(
    'root' => array(
        'name' => 'bitapps/pi',
        'pretty_version' => '0.3.0',
        'version' => '0.3.0.0',
        'reference' => '98596d34ea4a91533b87f31e3edd7574f3384650',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'bitapps/pi' => array(
            'pretty_version' => '0.3.0',
            'version' => '0.3.0.0',
            'reference' => '98596d34ea4a91533b87f31e3edd7574f3384650',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bitapps/wp-database' => array(
            'pretty_version' => '1.9',
            'version' => '1.9.0.0',
            'reference' => '8ffec3938db1d598be79ed34f39928b607673d87',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bitapps/wp-database',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bitapps/wp-kit' => array(
            'pretty_version' => '1.7',
            'version' => '1.7.0.0',
            'reference' => '37282f745e13161fddbe9e0b9c9ddf9f1be85e63',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bitapps/wp-kit',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bitapps/wp-telemetry' => array(
            'pretty_version' => 'v0.0.8',
            'version' => '0.0.8.0',
            'reference' => 'efa19cfc72e6325889e6bcd78bdd45556f9aa1a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bitapps/wp-telemetry',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bitapps/wp-validator' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '294d6a7c35436419060dc067f58a9c5a0d72b37e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bitapps/wp-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typisttech/imposter' => array(
            'pretty_version' => '0.6.1',
            'version' => '0.6.1.0',
            'reference' => 'f52b1a2289d2ea9c660cf9595085d0b11469af83',
            'type' => 'library',
            'install_path' => __DIR__ . '/../typisttech/imposter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typisttech/imposter-plugin' => array(
            'pretty_version' => '0.6.2',
            'version' => '0.6.2.0',
            'reference' => '15fa3c90aca3b79497f438b9e02a6176498de53c',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../typisttech/imposter-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
