<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit801636cb430d6b4ba7041ea15f382212
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Appsero\\' => 8,
            'ADQS_Directory\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Appsero\\' => 
        array (
            0 => __DIR__ . '/..' . '/appsero/client/src',
        ),
        'ADQS_Directory\\' => 
        array (
            0 => __DIR__ . '/../..' . '/inc',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit801636cb430d6b4ba7041ea15f382212::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit801636cb430d6b4ba7041ea15f382212::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit801636cb430d6b4ba7041ea15f382212::$classMap;

        }, null, ClassLoader::class);
    }
}
