<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit538f90c3883f674f56e450e4fd6b4c20
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'EasyEddForElementor\\Widgets\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'EasyEddForElementor\\Widgets\\' => 
        array (
            0 => __DIR__ . '/../..' . '/widgets',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit538f90c3883f674f56e450e4fd6b4c20::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit538f90c3883f674f56e450e4fd6b4c20::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit538f90c3883f674f56e450e4fd6b4c20::$classMap;

        }, null, ClassLoader::class);
    }
}
