<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Appsero\\Client' => $vendorDir . '/appsero/client/src/Client.php',
    'Appsero\\Insights' => $vendorDir . '/appsero/client/src/Insights.php',
    'Appsero\\License' => $vendorDir . '/appsero/client/src/License.php',
    'Automattic\\Jetpack\\Autoloader\\AutoloadFileWriter' => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadFileWriter.php',
    'Automattic\\Jetpack\\Autoloader\\AutoloadGenerator' => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadGenerator.php',
    'Automattic\\Jetpack\\Autoloader\\AutoloadProcessor' => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadProcessor.php',
    'Automattic\\Jetpack\\Autoloader\\CustomAutoloaderPlugin' => $vendorDir . '/automattic/jetpack-autoloader/src/CustomAutoloaderPlugin.php',
    'Automattic\\Jetpack\\Autoloader\\ManifestGenerator' => $vendorDir . '/automattic/jetpack-autoloader/src/ManifestGenerator.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Optemiz\\AWO\\Admin' => $baseDir . '/includes/Admin.php',
    'Optemiz\\AWO\\Admin_Menu' => $baseDir . '/includes/Admin_Menu.php',
    'Optemiz\\AWO\\Admin_Notices' => $baseDir . '/includes/Admin_Notices.php',
    'Optemiz\\AWO\\Admin_Page' => $baseDir . '/includes/Admin_Page.php',
    'Optemiz\\AWO\\Assets' => $baseDir . '/includes/Assets.php',
    'Optemiz\\AWO\\AutoComplete_Orders' => $baseDir . '/includes/AutoComplete_Orders.php',
    'Optemiz\\AWO\\Frontend' => $baseDir . '/includes/Frontend.php',
    'Optemiz\\AWO\\Metaboxes' => $baseDir . '/includes/Metaboxes.php',
    'Optemiz\\AWO\\Settings' => $baseDir . '/includes/Settings.php',
    'Optemiz\\Dashboard\\AbstractField' => $vendorDir . '/optemiz/dashboard/includes/AbstractField.php',
    'Optemiz\\Dashboard\\AbstractTab' => $vendorDir . '/optemiz/dashboard/includes/AbstractTab.php',
    'Optemiz\\Dashboard\\Field' => $vendorDir . '/optemiz/dashboard/includes/Field.php',
    'Optemiz\\Dashboard\\Header' => $vendorDir . '/optemiz/dashboard/includes/Header.php',
    'Optemiz\\Dashboard\\Settings' => $vendorDir . '/optemiz/dashboard/includes/Settings.php',
    'Optemiz\\Dashboard\\Sidebar' => $vendorDir . '/optemiz/dashboard/includes/Sidebar.php',
    'Optemiz\\Dashboard\\SubTab' => $vendorDir . '/optemiz/dashboard/includes/SubTab.php',
    'Optemiz\\Dashboard\\Tab' => $vendorDir . '/optemiz/dashboard/includes/Tab.php',
);
