<?php

/**
 *    __  _____   ___   __          __
 *   / / / /   | <  /  / /   ____ _/ /_  _____
 *  / / / / /| | / /  / /   / __ `/ __ `/ ___/
 * / /_/ / ___ |/ /  / /___/ /_/ / /_/ (__  )
 * `____/_/  |_/_/  /_____/`__,_/_.___/____/
 *
 * @package FireStudio
 * @author UA1 Labs Developers https://ua1.us
 * @copyright Copyright (c) UA1 Labs
 */

?>

<span class="firestudio-logo">
    <img src="<?php echo $this->e($this->logo); ?>" alt="<?php echo $this->t('firestudio logo'); ?>">
</span>
<?php echo $this->t('FireStudio') ?>