<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita7a9a74035bf63d2f1edd42d68f2dd18
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WooCommerceVariationSwatches\\' => 29,
        ),
        'B' => 
        array (
            'ByteKit\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WooCommerceVariationSwatches\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
        'ByteKit\\' => 
        array (
            0 => __DIR__ . '/..' . '/byteever/bytekit-plugin/src',
        ),
    );

    public static $classMap = array (
        'ByteKit\\Admin\\Flash' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Flash.php',
        'ByteKit\\Admin\\Notices' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Notices.php',
        'ByteKit\\Interfaces\\Pluginable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
        'ByteKit\\Interfaces\\Scriptable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
        'ByteKit\\Plugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Plugin.php',
        'ByteKit\\Scripts' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Scripts.php',
        'ByteKit\\Services' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Services.php',
        'ByteKit\\Traits\\HasPlugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WooCommerceVariationSwatches\\Admin\\Admin' => __DIR__ . '/../..' . '/includes/Admin/Admin.php',
        'WooCommerceVariationSwatches\\Admin\\Notices' => __DIR__ . '/../..' . '/includes/Admin/Notices.php',
        'WooCommerceVariationSwatches\\Admin\\Settings' => __DIR__ . '/../..' . '/includes/Admin/Settings.php',
        'WooCommerceVariationSwatches\\Admin\\SettingsAPI' => __DIR__ . '/../..' . '/includes/Admin/SettingsAPI.php',
        'WooCommerceVariationSwatches\\Plugin' => __DIR__ . '/../..' . '/includes/Plugin.php',
        'WooCommerceVariationSwatches\\Products' => __DIR__ . '/../..' . '/includes/Products.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita7a9a74035bf63d2f1edd42d68f2dd18::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita7a9a74035bf63d2f1edd42d68f2dd18::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita7a9a74035bf63d2f1edd42d68f2dd18::$classMap;

        }, null, ClassLoader::class);
    }
}
