<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AutocompleteOrdersForWooCommerce\\Admin\\Admin' => $baseDir . '/includes/Admin/Admin.php',
    'AutocompleteOrdersForWooCommerce\\Admin\\Notices' => $baseDir . '/includes/Admin/Notices.php',
    'AutocompleteOrdersForWooCommerce\\Orders' => $baseDir . '/includes/Orders.php',
    'AutocompleteOrdersForWooCommerce\\Plugin' => $baseDir . '/includes/Plugin.php',
    'ByteKit\\Admin\\Flash' => $vendorDir . '/byteever/bytekit-plugin/src/Admin/Flash.php',
    'ByteKit\\Admin\\Notices' => $vendorDir . '/byteever/bytekit-plugin/src/Admin/Notices.php',
    'ByteKit\\Interfaces\\Pluginable' => $vendorDir . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
    'ByteKit\\Interfaces\\Scriptable' => $vendorDir . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
    'ByteKit\\Plugin' => $vendorDir . '/byteever/bytekit-plugin/src/Plugin.php',
    'ByteKit\\Scripts' => $vendorDir . '/byteever/bytekit-plugin/src/Scripts.php',
    'ByteKit\\Services' => $vendorDir . '/byteever/bytekit-plugin/src/Services.php',
    'ByteKit\\Traits\\HasPlugin' => $vendorDir . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
