<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Lkngc\\CryptocurrencyForGivewp\\PublicView\\' => array($baseDir . '/Public'),
    'Lkngc\\CryptocurrencyForGivewp\\Includes\\' => array($baseDir . '/Includes'),
    'Lkngc\\CryptocurrencyForGivewp\\Admin\\' => array($baseDir . '/Admin'),
);
