<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '65e023e5408b48c8a4eaebc6305d0f67' => $baseDir . '/includes/core.php',
    'da21c6669493ba905cb2932f5e08db45' => $baseDir . '/includes/codestar/codestar-framework.php',
);
