<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb104c0df0d70306b0c1230e99b7d5c9c
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'CoffeCode\\ExtraShippingMethods\\' => 31,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'CoffeCode\\ExtraShippingMethods\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb104c0df0d70306b0c1230e99b7d5c9c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb104c0df0d70306b0c1230e99b7d5c9c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb104c0df0d70306b0c1230e99b7d5c9c::$classMap;

        }, null, ClassLoader::class);
    }
}
