<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9daaacbfc24f4b464d2c5ec048822203
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Flynax\\Plugins\\FlynaxBridge\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Flynax\\Plugins\\FlynaxBridge\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9daaacbfc24f4b464d2c5ec048822203::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9daaacbfc24f4b464d2c5ec048822203::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9daaacbfc24f4b464d2c5ec048822203::$classMap;

        }, null, ClassLoader::class);
    }
}
