<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5fab9c2b8de1dfe43759ae52907acc2f
{
    public static $files = array (
        '60799491728b879e74601d83e38b2cad' => __DIR__ . '/..' . '/illuminate/collections/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\SimpleCache\\' => 16,
            'Psr\\Container\\' => 14,
        ),
        'I' => 
        array (
            'Illuminate\\Support\\' => 19,
            'Illuminate\\Contracts\\' => 21,
        ),
        'A' => 
        array (
            'AOP\\Test\\' => 9,
            'AOP\\Lib\\' => 8,
            'AOP\\App\\Options\\' => 16,
            'AOP\\App\\Database\\' => 17,
            'AOP\\App\\Admin\\' => 14,
            'AOP\\App\\' => 8,
            'AOP\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Illuminate\\Support\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/collections',
            1 => __DIR__ . '/..' . '/illuminate/conditionable',
            2 => __DIR__ . '/..' . '/illuminate/macroable',
        ),
        'Illuminate\\Contracts\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/contracts',
        ),
        'AOP\\Test\\' => 
        array (
            0 => __DIR__ . '/../..' . '/test',
        ),
        'AOP\\Lib\\' => 
        array (
            0 => __DIR__ . '/../..' . '/lib',
        ),
        'AOP\\App\\Options\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app/options',
        ),
        'AOP\\App\\Database\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app/database',
        ),
        'AOP\\App\\Admin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app/admin',
        ),
        'AOP\\App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
        'AOP\\' => 
        array (
            0 => __DIR__ . '/../..' . '/',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5fab9c2b8de1dfe43759ae52907acc2f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5fab9c2b8de1dfe43759ae52907acc2f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5fab9c2b8de1dfe43759ae52907acc2f::$classMap;

        }, null, ClassLoader::class);
    }
}
