<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9a03694fbf8c19d33a11828b26b3b4a6
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Masterminds\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Masterminds\\' => 
        array (
            0 => __DIR__ . '/..' . '/masterminds/html5/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'H' => 
        array (
            'Hametuha\\ForYourEyesOnly' => 
            array (
                0 => __DIR__ . '/../..' . '/app',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9a03694fbf8c19d33a11828b26b3b4a6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9a03694fbf8c19d33a11828b26b3b4a6::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit9a03694fbf8c19d33a11828b26b3b4a6::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit9a03694fbf8c19d33a11828b26b3b4a6::$classMap;

        }, null, ClassLoader::class);
    }
}
