<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3de4af3b4286b390214179267289e6fd
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tweaks\\Dependencies\\' => 20,
            'Tweaks\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tweaks\\Dependencies\\' => 
        array (
            0 => __DIR__ . '/../..' . '/dependencies',
        ),
        'Tweaks\\' => 
        array (
            0 => __DIR__ . '/../..' . '/classes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Tweaks\\Dependencies\\Parsedown' => __DIR__ . '/../..' . '/dependencies/Parsedown.php',
        'Tweaks\\Dependencies\\WP_Options_Page' => __DIR__ . '/../..' . '/dependencies/WP_Options_Page.php',
        'Tweaks\\Markdown' => __DIR__ . '/../..' . '/classes/Markdown.php',
        'Tweaks\\Settings' => __DIR__ . '/../..' . '/classes/Settings.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3de4af3b4286b390214179267289e6fd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3de4af3b4286b390214179267289e6fd::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3de4af3b4286b390214179267289e6fd::$classMap;

        }, null, ClassLoader::class);
    }
}
