<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf9274739de8efc2f1aaa563c0feb19a3
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FormInteg\\IKLAVIYOEF\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FormInteg\\IKLAVIYOEF\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FormInteg\\IKLAVIYOEF\\Actions\\ActionController' => __DIR__ . '/../..' . '/includes/Actions/ActionController.php',
        'FormInteg\\IKLAVIYOEF\\Actions\\Klaviyo\\KlaviyoController' => __DIR__ . '/../..' . '/includes/Actions/Klaviyo/KlaviyoController.php',
        'FormInteg\\IKLAVIYOEF\\Actions\\Klaviyo\\RecordApiHelper' => __DIR__ . '/../..' . '/includes/Actions/Klaviyo/RecordApiHelper.php',
        'FormInteg\\IKLAVIYOEF\\Admin\\AdminAjax' => __DIR__ . '/../..' . '/includes/Admin/AdminAjax.php',
        'FormInteg\\IKLAVIYOEF\\Admin\\Admin_Bar' => __DIR__ . '/../..' . '/includes/Admin/Admin_Bar.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Database\\DB' => __DIR__ . '/../..' . '/includes/Core/Database/DB.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Database\\FlowModel' => __DIR__ . '/../..' . '/includes/Core/Database/FlowModel.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Database\\LogModel' => __DIR__ . '/../..' . '/includes/Core/Database/LogModel.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Database\\Model' => __DIR__ . '/../..' . '/includes/Core/Database/Model.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Hooks\\HookService' => __DIR__ . '/../..' . '/includes/Core/Hooks/HookService.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\API' => __DIR__ . '/../..' . '/includes/Core/Util/API.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Activation' => __DIR__ . '/../..' . '/includes/Core/Util/Activation.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Capabilities' => __DIR__ . '/../..' . '/includes/Core/Util/Capabilities.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Common' => __DIR__ . '/../..' . '/includes/Core/Util/Common.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\DateTimeHelper' => __DIR__ . '/../..' . '/includes/Core/Util/DateTimeHelper.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Deactivation' => __DIR__ . '/../..' . '/includes/Core/Util/Deactivation.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Helper' => __DIR__ . '/../..' . '/includes/Core/Util/Helper.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Hooks' => __DIR__ . '/../..' . '/includes/Core/Util/Hooks.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\HttpHelper' => __DIR__ . '/../..' . '/includes/Core/Util/HttpHelper.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\IpTool' => __DIR__ . '/../..' . '/includes/Core/Util/IpTool.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Multisite' => __DIR__ . '/../..' . '/includes/Core/Util/Multisite.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Request' => __DIR__ . '/../..' . '/includes/Core/Util/Request.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\Route' => __DIR__ . '/../..' . '/includes/Core/Util/Route.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\SmartTags' => __DIR__ . '/../..' . '/includes/Core/Util/SmartTags.php',
        'FormInteg\\IKLAVIYOEF\\Core\\Util\\UnInstallation' => __DIR__ . '/../..' . '/includes/Core/Util/UnInstallation.php',
        'FormInteg\\IKLAVIYOEF\\Flow\\Flow' => __DIR__ . '/../..' . '/includes/Flow/Flow.php',
        'FormInteg\\IKLAVIYOEF\\Flow\\FlowController' => __DIR__ . '/../..' . '/includes/Flow/FlowController.php',
        'FormInteg\\IKLAVIYOEF\\Log\\LogHandler' => __DIR__ . '/../..' . '/includes/Log/LogHandler.php',
        'FormInteg\\IKLAVIYOEF\\Plugin' => __DIR__ . '/../..' . '/includes/Plugin.php',
        'FormInteg\\IKLAVIYOEF\\Triggers\\Elementor\\ElementorController' => __DIR__ . '/../..' . '/includes/Triggers/Elementor/ElementorController.php',
        'FormInteg\\IKLAVIYOEF\\Triggers\\Elementor\\ElementorHelper' => __DIR__ . '/../..' . '/includes/Triggers/Elementor/ElementorHelper.php',
        'FormInteg\\IKLAVIYOEF\\Triggers\\TriggerController' => __DIR__ . '/../..' . '/includes/Triggers/TriggerController.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf9274739de8efc2f1aaa563c0feb19a3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf9274739de8efc2f1aaa563c0feb19a3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf9274739de8efc2f1aaa563c0feb19a3::$classMap;

        }, null, ClassLoader::class);
    }
}
