<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitba1ceaf377690653b81e8a3c68628825
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Prokerala_WP_Astrology_Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Prokerala_WP_Astrology_Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitba1ceaf377690653b81e8a3c68628825', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Prokerala_WP_Astrology_Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitba1ceaf377690653b81e8a3c68628825', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Prokerala_WP_Astrology_Composer\Autoload\ComposerStaticInitba1ceaf377690653b81e8a3c68628825::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
