<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7875ee5a7fe272ce81b3709b19d0cd1d
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DavidWenner\\ATestimonialBuilder\\' => 32,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DavidWenner\\ATestimonialBuilder\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7875ee5a7fe272ce81b3709b19d0cd1d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7875ee5a7fe272ce81b3709b19d0cd1d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7875ee5a7fe272ce81b3709b19d0cd1d::$classMap;

        }, null, ClassLoader::class);
    }
}
