<?php return array(
    'root' => array(
        'name' => '1984/1984-connector-for-dk-and-woocommerce',
        'pretty_version' => '0.4.5.2',
        'version' => '0.4.5.2',
        'reference' => null,
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        '1984/1984-connector-for-dk-and-woocommerce' => array(
            'pretty_version' => '0.4.5.2',
            'version' => '0.4.5.2',
            'reference' => null,
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.12.1',
            'version' => '0.12.1.0',
            'reference' => 'f510c0a40911935b77b86859eb5223d58d660df1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'opis/json-schema' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'd1389724c96f31335045c799207c79621268f177',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/json-schema',
            'aliases' => array(
                0 => '2.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'opis/string' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '9ebf1a1f873f502f6859d11210b25a4bf5d141e7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'opis/uri' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '0f3ca49ab1a5e4a6681c286e0b2cc081b93a7d5a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/uri',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typisttech/imposter' => array(
            'pretty_version' => '0.6.1',
            'version' => '0.6.1.0',
            'reference' => 'f52b1a2289d2ea9c660cf9595085d0b11469af83',
            'type' => 'library',
            'install_path' => __DIR__ . '/../typisttech/imposter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typisttech/imposter-plugin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '11d16a7af76dc08e47b05c3baca93036404b4f93',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../typisttech/imposter-plugin',
            'aliases' => array(
                0 => '0.6.x-dev',
            ),
            'dev_requirement' => false,
        ),
    ),
);
