<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite857e235c0988fb64b75b2eb23a4677a
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Bookster_Extra_Options\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Bookster_Extra_Options\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite857e235c0988fb64b75b2eb23a4677a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite857e235c0988fb64b75b2eb23a4677a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite857e235c0988fb64b75b2eb23a4677a::$classMap;

        }, null, ClassLoader::class);
    }
}
