<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'TypistTech\\WPContainedHook\\' => array($vendorDir . '/typisttech/wp-contained-hook/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'League\\Container\\' => array($vendorDir . '/league/container/src'),
    'Itineris\\DisallowPwnedPasswords\\' => array($baseDir . '/src'),
);
