<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'automattic/jetpack-autoloader' => array(
            'pretty_version' => 'v3.1.3',
            'version' => '3.1.3.0',
            'reference' => 'e7e49a4e2f16cb2dfd3e58c478499a60d7d51839',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../automattic/jetpack-autoloader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'automattic/jetpack-constants' => array(
            'pretty_version' => 'v2.0.5',
            'version' => '2.0.5.0',
            'reference' => '0c2644d642b06ae2a31c561f5bfc6f74a4abc8f1',
            'type' => 'jetpack-library',
            'install_path' => __DIR__ . '/../automattic/jetpack-constants',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chillerlan/php-qrcode' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '42e215640e9ebdd857570c9e4e52245d1ee51de2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-qrcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chillerlan/php-settings-container' => array(
            'pretty_version' => '2.1.6',
            'version' => '2.1.6.0',
            'reference' => '5553558bd381fce5108c6d0343c12e488cfec6bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-settings-container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/serializable-closure' => array(
            'pretty_version' => 'v1.3.7',
            'version' => '1.3.7.0',
            'reference' => '4f48ade902b94323ca3be7646db16209ec76be3d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/serializable-closure',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'oblak/admin-notice-manager' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'oblak/serbian-validators' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'dafbd9877950a77dabe4ff6325e0b7e429e853eb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../oblak/serbian-validators',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'oblak/wp-plugin-installer' => array(
            'pretty_version' => 'v2.1.5',
            'version' => '2.1.5.0',
            'reference' => '699d8f4788d1925d22b2f816f2b8285be09b6354',
            'type' => 'library',
            'install_path' => __DIR__ . '/../oblak/wp-plugin-installer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-di/invoker' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'reference' => '33234b32dafa8eb69202f950a1fc92055ed76a86',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-di/invoker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-di/php-di' => array(
            'pretty_version' => '7.0.7',
            'version' => '7.0.7.0',
            'reference' => 'e87435e3c0e8f22977adc5af0d5cdcc467e15cf1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-di/php-di',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => '4a4cfc2d253c21a5ad0e53071df248ed48c6ce5c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woocommerce/action-scheduler' => array(
            'pretty_version' => '3.9.0',
            'version' => '3.9.0.0',
            'reference' => '90b98e6fe97d455679b1d288f050cad8f6f79771',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../woocommerce/action-scheduler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'x-wp/admin-notice-manager' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '61bfbf90f90117d24af5130bbc80911b1c10f3cc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../x-wp/admin-notice-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'x-wp/asset-loader' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'f4a445e27fc913c20ab42ac7467b83514b750794',
            'type' => 'library',
            'install_path' => __DIR__ . '/../x-wp/asset-loader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'x-wp/asset-loader-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'x-wp/di' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '3cea33921ef8cf1cab14a1da88ffe43d168bcce1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../x-wp/di',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'x-wp/di-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'x-wp/helper-classes' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'reference' => '451dff53964c2fbdf086882c868709e4e36fb1cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../x-wp/helper-classes',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'x-wp/helper-functions' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'reference' => 'edd258d0b2ad90a78893ffcabf6626cebf56a281',
            'type' => 'library',
            'install_path' => __DIR__ . '/../x-wp/helper-functions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'x-wp/helper-traits' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'reference' => '0367d136d6ba36e2ae0fe1854584ef760ea7cae9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../x-wp/helper-traits',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'x-wp/helper-woocommerce' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'reference' => '8429f9ed7612fe2e09862548aba8d09b1324177f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../x-wp/helper-woocommerce',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'x-wp/hook-invoker' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'x-wp/wc-template-customizer' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b38df4993b8fbefe0af0f27f44be4bb853418465',
            'type' => 'library',
            'install_path' => __DIR__ . '/../x-wp/wc-template-customizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
