<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit815bed5aee29d31f69a50f13985761a3
{
    public static $files = array (
        'ac949ce40a981819ba132473518a9a31' => __DIR__ . '/..' . '/wp-cli/wp-config-transformer/src/WPConfigTransformer.php',
    );

    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'AdminDebugTools\\Plugin\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'AdminDebugTools\\Plugin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'AdminDebugTools\\Plugin\\Bootstrap\\Admin\\Pages' => __DIR__ . '/../..' . '/includes/Bootstrap/Admin/Pages.php',
        'AdminDebugTools\\Plugin\\Container' => __DIR__ . '/../..' . '/includes/Container.php',
        'AdminDebugTools\\Plugin\\Core\\FileContent' => __DIR__ . '/../..' . '/includes/Core/FileContent.php',
        'AdminDebugTools\\Plugin\\Core\\FileContentGetter' => __DIR__ . '/../..' . '/includes/Core/FileContentGetter.php',
        'AdminDebugTools\\Plugin\\Core\\FileContentLine' => __DIR__ . '/../..' . '/includes/Core/FileContentLine.php',
        'AdminDebugTools\\Plugin\\Core\\LogLine' => __DIR__ . '/../..' . '/includes/Core/LogLine.php',
        'AdminDebugTools\\Plugin\\Core\\LogLineCollection' => __DIR__ . '/../..' . '/includes/Core/LogLineCollection.php',
        'AdminDebugTools\\Plugin\\Core\\LogParser' => __DIR__ . '/../..' . '/includes/Core/LogParser.php',
        'AdminDebugTools\\Plugin\\Core\\SseServer' => __DIR__ . '/../..' . '/includes/Core/SseServer.php',
        'AdminDebugTools\\Plugin\\Core\\WpLogParser' => __DIR__ . '/../..' . '/includes/Core/WpLogParser.php',
        'AdminDebugTools\\Plugin\\Exceptions\\Container\\ContainerException' => __DIR__ . '/../..' . '/includes/Exceptions/Container/ContainerException.php',
        'AdminDebugTools\\Plugin\\Exceptions\\Container\\NotFoundException' => __DIR__ . '/../..' . '/includes/Exceptions/Container/NotFoundException.php',
        'AdminDebugTools\\Plugin\\Exceptions\\Exception' => __DIR__ . '/../..' . '/includes/Exceptions/Exception.php',
        'AdminDebugTools\\Plugin\\Exceptions\\RestApi\\AuthorizationException' => __DIR__ . '/../..' . '/includes/Exceptions/RestApi/AuthorizationException.php',
        'AdminDebugTools\\Plugin\\Exceptions\\RestApi\\InvalidParamException' => __DIR__ . '/../..' . '/includes/Exceptions/RestApi/InvalidParamException.php',
        'AdminDebugTools\\Plugin\\Exceptions\\RestApi\\RestApiException' => __DIR__ . '/../..' . '/includes/Exceptions/RestApi/RestApiException.php',
        'AdminDebugTools\\Plugin\\Exceptions\\UserFrienldlyException' => __DIR__ . '/../..' . '/includes/Exceptions/UserFrienldlyException.php',
        'AdminDebugTools\\Plugin\\Options\\Options' => __DIR__ . '/../..' . '/includes/Options/Options.php',
        'AdminDebugTools\\Plugin\\Plugin' => __DIR__ . '/../..' . '/includes/Plugin.php',
        'AdminDebugTools\\Plugin\\RestApi\\Controllers\\BaseController' => __DIR__ . '/../..' . '/includes/RestApi/Controllers/BaseController.php',
        'AdminDebugTools\\Plugin\\RestApi\\Controllers\\DebugLogController' => __DIR__ . '/../..' . '/includes/RestApi/Controllers/DebugLogController.php',
        'AdminDebugTools\\Plugin\\RestApi\\Controllers\\WpConfigController' => __DIR__ . '/../..' . '/includes/RestApi/Controllers/WpConfigController.php',
        'AdminDebugTools\\Plugin\\RestApi\\RestApi' => __DIR__ . '/../..' . '/includes/RestApi/RestApi.php',
        'AdminDebugTools\\Plugin\\Utils\\Arr' => __DIR__ . '/../..' . '/includes/Utils/Arr.php',
        'AdminDebugTools\\Plugin\\Utils\\Asset' => __DIR__ . '/../..' . '/includes/Utils/Asset.php',
        'AdminDebugTools\\Plugin\\Utils\\Date' => __DIR__ . '/../..' . '/includes/Utils/Date.php',
        'AdminDebugTools\\Plugin\\Utils\\Filesystem' => __DIR__ . '/../..' . '/includes/Utils/Filesystem.php',
        'AdminDebugTools\\Plugin\\Utils\\Utils' => __DIR__ . '/../..' . '/includes/Utils/Utils.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit815bed5aee29d31f69a50f13985761a3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit815bed5aee29d31f69a50f13985761a3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit815bed5aee29d31f69a50f13985761a3::$classMap;

        }, null, ClassLoader::class);
    }
}
