<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Alter\\Admin\\Init' => $baseDir . '/src/Admin/Controllers/Init.php',
    'Alter\\Core\\Activator' => $baseDir . '/src/Core/Controllers/Activator.php',
    'Alter\\Core\\Deactivator' => $baseDir . '/src/Core/Controllers/Deactivator.php',
    'Alter\\Core\\Init' => $baseDir . '/src/Core/Controllers/Init.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'MatterWP\\WPSubscriptionManager\\Config' => $vendorDir . '/matterwp/wp-subscription-manager/src/Config.php',
    'MatterWP\\WPSubscriptionManager\\Diagnosis' => $vendorDir . '/matterwp/wp-subscription-manager/src/Diagnosis.php',
    'MatterWP\\WPSubscriptionManager\\SubscriptionManager' => $vendorDir . '/matterwp/wp-subscription-manager/src/SubscriptionManager.php',
    'MatterWP\\WPSubscriptionManager\\SubscriptionManagerFactory' => $vendorDir . '/matterwp/wp-subscription-manager/src/SubscriptionManagerFactory.php',
    'MatterWP\\WPSubscriptionManager\\WelcomePage' => $vendorDir . '/matterwp/wp-subscription-manager/src/WelcomePage.php',
);
