<?php

/**
 * LandingPageApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BenefitPlusGatewaySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Benefit Plus e-commerce payment gateway 3
 *
 * This is a \"swagger\" definition of application programming interface of the Benefit Plus e-commerce payment gateway 3. You may leverage this API from your e-shop to integrate payments by employee-benefits-programme funds. This version of the programme uses mobile payment application Benefit Plus Pay. <br/><br/>RFC version - this is a conceptual document intended for reviewing by the Benefit Plus partnering merchants and for integration planning.</br></br> <b>Requests signing</b></br></br>All requests except <code>/auth/token</code> must be signed by \"SHA-256 with RSA\" (RSASSA-PKCS1-v1_5,  <a href=\"https://datatracker.ietf.org/doc/html/rfc8017#section-8.2\" target=\"_blank\" rel=\"noopener noreferrer\">RFC 8017 chapter 8.2</a>) electronic signatures. See online gateway documentation for details.
 *
 * The version of the OpenAPI document: 1.0.RFC8
 * Contact: partneri@benefit-plus.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace MuzaPayDeps\BenefitPlusGatewaySdk\Api;

use MuzaPayDeps\GuzzleHttp\Client;
use MuzaPayDeps\GuzzleHttp\ClientInterface;
use MuzaPayDeps\GuzzleHttp\Exception\ConnectException;
use MuzaPayDeps\GuzzleHttp\Exception\RequestException;
use MuzaPayDeps\GuzzleHttp\Psr7\MultipartStream;
use MuzaPayDeps\GuzzleHttp\Psr7\Request;
use MuzaPayDeps\GuzzleHttp\RequestOptions;
use MuzaPayDeps\BenefitPlusGatewaySdk\ApiException;
use MuzaPayDeps\BenefitPlusGatewaySdk\Configuration;
use MuzaPayDeps\BenefitPlusGatewaySdk\HeaderSelector;
use MuzaPayDeps\BenefitPlusGatewaySdk\ObjectSerializer;
/**
 * LandingPageApi Class Doc Comment
 *
 * @category Class
 * @package  BenefitPlusGatewaySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LandingPageApi
{
    /**
     * @var ClientInterface
     */
    protected $client;
    /**
     * @var Configuration
     */
    protected $config;
    /**
     * @var HeaderSelector
     */
    protected $headerSelector;
    /**
     * @var int Host index
     */
    protected $hostIndex;
    /** @var string[] $contentTypes **/
    public const contentTypes = ['getLandingPage' => ['application/json']];
    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(ClientInterface $client = null, Configuration $config = null, HeaderSelector $selector = null, $hostIndex = 0)
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }
    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }
    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }
    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }
    /**
     * Operation getLandingPage
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getLandingPage'] to see the possible values for this operation
     *
     * @throws \BenefitPlusGatewaySdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function getLandingPage(string $contentType = self::contentTypes['getLandingPage'][0])
    {
        list($response) = $this->getLandingPageWithHttpInfo($contentType);
        return $response;
    }
    /**
     * Operation getLandingPageWithHttpInfo
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getLandingPage'] to see the possible values for this operation
     *
     * @throws \BenefitPlusGatewaySdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function getLandingPageWithHttpInfo(string $contentType = self::contentTypes['getLandingPage'][0])
    {
        $request = $this->getLandingPageRequest($contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            switch ($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody();
                        //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    return [ObjectSerializer::deserialize($content, 'string', []), $response->getStatusCode(), $response->getHeaders()];
            }
            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }
    /**
     * Operation getLandingPageAsync
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getLandingPage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getLandingPageAsync(string $contentType = self::contentTypes['getLandingPage'][0])
    {
        return $this->getLandingPageAsyncWithHttpInfo($contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation getLandingPageAsyncWithHttpInfo
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getLandingPage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getLandingPageAsyncWithHttpInfo(string $contentType = self::contentTypes['getLandingPage'][0])
    {
        $returnType = 'string';
        $request = $this->getLandingPageRequest($contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'getLandingPage'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getLandingPage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getLandingPageRequest(string $contentType = self::contentTypes['getLandingPage'][0])
    {
        $resourcePath = '/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        $headers = $this->headerSelector->selectHeaders(['text/plain'], $contentType, $multipart);
        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \MuzaPayDeps\GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }
        return $options;
    }
}
