<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1888c1738123fcd3e3b23d63a08eab09
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MatterWP\\WPSubscriptionManager\\' => 31,
        ),
        'A' => 
        array (
            'Alter\\Core\\' => 11,
            'Alter\\Admin\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MatterWP\\WPSubscriptionManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/matterwp/wp-subscription-manager/src',
        ),
        'Alter\\Core\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Core/Controllers',
        ),
        'Alter\\Admin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Admin/Controllers',
        ),
    );

    public static $classMap = array (
        'Alter\\Admin\\Init' => __DIR__ . '/../..' . '/src/Admin/Controllers/Init.php',
        'Alter\\Core\\Activator' => __DIR__ . '/../..' . '/src/Core/Controllers/Activator.php',
        'Alter\\Core\\Deactivator' => __DIR__ . '/../..' . '/src/Core/Controllers/Deactivator.php',
        'Alter\\Core\\Init' => __DIR__ . '/../..' . '/src/Core/Controllers/Init.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'MatterWP\\WPSubscriptionManager\\Config' => __DIR__ . '/..' . '/matterwp/wp-subscription-manager/src/Config.php',
        'MatterWP\\WPSubscriptionManager\\Diagnosis' => __DIR__ . '/..' . '/matterwp/wp-subscription-manager/src/Diagnosis.php',
        'MatterWP\\WPSubscriptionManager\\SubscriptionManager' => __DIR__ . '/..' . '/matterwp/wp-subscription-manager/src/SubscriptionManager.php',
        'MatterWP\\WPSubscriptionManager\\SubscriptionManagerFactory' => __DIR__ . '/..' . '/matterwp/wp-subscription-manager/src/SubscriptionManagerFactory.php',
        'MatterWP\\WPSubscriptionManager\\WelcomePage' => __DIR__ . '/..' . '/matterwp/wp-subscription-manager/src/WelcomePage.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1888c1738123fcd3e3b23d63a08eab09::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1888c1738123fcd3e3b23d63a08eab09::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1888c1738123fcd3e3b23d63a08eab09::$classMap;

        }, null, ClassLoader::class);
    }
}
