<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0fz406a26e5822026585994168db593c
{
    public static $files = array (
        '7166494aeff09009178f278afd86c83f' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v4p13.php',
    );

    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Rankology_Stats\\Detailed_Data\\' => 24,
            'Rankology_Stats\\AdvancedDataPlus\\Vendor\\TeamRankology\\Updater\\' => 57,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Rankology_Stats\\Detailed_Data\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'Rankology_Stats\\AdvancedDataPlus\\Vendor\\TeamRankology\\Updater\\' => 
        array (
            0 => __DIR__ . '/..' . '/teamrankology/updater/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        //var_dump(ComposerStaticInit0fz406a26e5822026585994168db593c::$prefixDirsPsr4); die;
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0fz406a26e5822026585994168db593c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0fz406a26e5822026585994168db593c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0fz406a26e5822026585994168db593c::$classMap;

        }, null, ClassLoader::class);
    }
}
