<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Autoblue\\Admin' => $baseDir . '/includes/Admin.php',
    'Autoblue\\Assets' => $baseDir . '/includes/Assets.php',
    'Autoblue\\Blocks' => $baseDir . '/includes/Blocks.php',
    'Autoblue\\Bluesky' => $baseDir . '/includes/Bluesky.php',
    'Autoblue\\Bluesky\\API' => $baseDir . '/includes/Bluesky/API.php',
    'Autoblue\\Bluesky\\TextParser' => $baseDir . '/includes/Bluesky/TextParser.php',
    'Autoblue\\CLI\\Commands' => $baseDir . '/includes/CLI/Commands.php',
    'Autoblue\\CLI\\Logs' => $baseDir . '/includes/CLI/Logs.php',
    'Autoblue\\Comments' => $baseDir . '/includes/Comments.php',
    'Autoblue\\ConnectionsManager' => $baseDir . '/includes/ConnectionsManager.php',
    'Autoblue\\Endpoints\\AccountController' => $baseDir . '/includes/Endpoints/AccountController.php',
    'Autoblue\\Endpoints\\ConnectionsController' => $baseDir . '/includes/Endpoints/ConnectionsController.php',
    'Autoblue\\Endpoints\\LogsController' => $baseDir . '/includes/Endpoints/LogsController.php',
    'Autoblue\\Endpoints\\SearchController' => $baseDir . '/includes/Endpoints/SearchController.php',
    'Autoblue\\ImageCompressor' => $baseDir . '/includes/ImageCompressor.php',
    'Autoblue\\Logging\\DatabaseHandler' => $baseDir . '/includes/Logging/DatabaseHandler.php',
    'Autoblue\\Logging\\Log' => $baseDir . '/includes/Logging/Log.php',
    'Autoblue\\Logging\\LogRepository' => $baseDir . '/includes/Logging/LogRepository.php',
    'Autoblue\\Logging\\Setup' => $baseDir . '/includes/Logging/Setup.php',
    'Autoblue\\Logging\\WPProcessor' => $baseDir . '/includes/Logging/WPProcessor.php',
    'Autoblue\\Meta' => $baseDir . '/includes/Meta.php',
    'Autoblue\\PostHandler' => $baseDir . '/includes/PostHandler.php',
    'Autoblue\\Setup' => $baseDir . '/includes/Setup.php',
    'Autoblue\\Utils' => $baseDir . '/includes/Utils.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
