<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9c6963b3a28f62aca96453cbcfcf049c
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Refact\\ACFG\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Refact\\ACFG\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Refact\\ACFG\\Blocks\\Blocks' => __DIR__ . '/../..' . '/src/Blocks/Blocks.php',
        'Refact\\ACFG\\Blocks\\Settings' => __DIR__ . '/../..' . '/src/Blocks/Settings.php',
        'Refact\\ACFG\\RuleSet' => __DIR__ . '/../..' . '/src/RuleSet.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9c6963b3a28f62aca96453cbcfcf049c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9c6963b3a28f62aca96453cbcfcf049c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9c6963b3a28f62aca96453cbcfcf049c::$classMap;

        }, null, ClassLoader::class);
    }
}
