<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit58b46fd79cebd2fe3c45627a600e478f
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'EDD\\ExtensionUtils\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'EDD\\ExtensionUtils\\' => 
        array (
            0 => __DIR__ . '/..' . '/easydigitaldownloads/edd-addon-tools/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit58b46fd79cebd2fe3c45627a600e478f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit58b46fd79cebd2fe3c45627a600e478f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit58b46fd79cebd2fe3c45627a600e478f::$classMap;

        }, null, ClassLoader::class);
    }
}
