<?php

// This file `jetpack_autoload_psr4.php` was auto generated by automattic/jetpack-autoloader.

$vendorDir = dirname(__DIR__);
$baseDir   = dirname($vendorDir);

return array(
	'Symfony\\Polyfill\\Mbstring\\' => array(
		'version' => '1.30.0.0',
		'path'    => array( $vendorDir . '/symfony/polyfill-mbstring' )
	),
	'Automattic\\Jetpack\\Autoloader\\' => array(
		'version' => '2.12.0',
		'path'    => array( $vendorDir . '/automattic/jetpack-autoloader/src' )
	),
);
