<?php

/**
 * CurrencyTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BenefitPlusGatewaySdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Benefit Plus e-commerce payment gateway 3
 *
 * This is a \"swagger\" definition of application programming interface of the Benefit Plus e-commerce payment gateway 3. You may leverage this API from your e-shop to integrate payments by employee-benefits-programme funds. This version of the programme uses mobile payment application Benefit Plus Pay. <br/><br/>RFC version - this is a conceptual document intended for reviewing by the Benefit Plus partnering merchants and for integration planning.</br></br> <b>Requests signing</b></br></br>All requests except <code>/auth/token</code> must be signed by \"SHA-256 with RSA\" (RSASSA-PKCS1-v1_5,  <a href=\"https://datatracker.ietf.org/doc/html/rfc8017#section-8.2\" target=\"_blank\" rel=\"noopener noreferrer\">RFC 8017 chapter 8.2</a>) electronic signatures. See online gateway documentation for details.
 *
 * The version of the OpenAPI document: 1.0.RFC8
 * Contact: partneri@benefit-plus.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */
namespace MuzaPayDeps\BenefitPlusGatewaySdk\Test\Model;

use MuzaPayDeps\PHPUnit\Framework\TestCase;
/**
 * CurrencyTest Class Doc Comment
 *
 * @category    Class
 * @description Currency of the e-shop assigned in onboarding of your e-shop. Cannot be changed from e-shop.
 * @package     BenefitPlusGatewaySdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CurrencyTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }
    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }
    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }
    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }
    /**
     * Test "Currency"
     */
    public function testCurrency()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
