// Donation
export const CHANGE_DONATION_TYPE = 'CHANGE_DONATION_TYPE';
export const CHANGE_DONATION_AMOUNT = 'CHANGE_DONATION_AMOUNT';
export const CHANGE_DONATION_AMOUNT_OPTION = 'CHANGE_DONATION_AMOUNT_OPTION';

// Recurring Donation
export const CHANGE_RECURRING_DONATION_OPTIONS = 'CHANGE_RECURRING_DONATION_OPTIONS';

//CURRENCIES
export const CHANGE_DONATION_CURRENCY = 'CHANGE_DONATION_CURRENCY';
export const CHANGE_SYMBOL_CURRENCY = 'CHANGE_SYMBOL_CURRENCY';

export const RESTART_DONATE_STATE= 'RESTART_DONATE_STATE';
