<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8d0dc70d94eb20d3d4c46917dac00800
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MuzaPay\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MuzaPay\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'MuzaPay\\Api\\MuzaPayApi' => __DIR__ . '/../..' . '/src/Api/MuzaPayApi.php',
        'MuzaPay\\Features\\CheckoutIntegration' => __DIR__ . '/../..' . '/src/Features/CheckoutIntegration.php',
        'MuzaPay\\Features\\Gateway' => __DIR__ . '/../..' . '/src/Features/Gateway.php',
        'MuzaPay\\Features\\Woocommerce' => __DIR__ . '/../..' . '/src/Features/Woocommerce.php',
        'MuzaPay\\Managers\\ApiManager' => __DIR__ . '/../..' . '/src/Managers/ApiManager.php',
        'MuzaPay\\Managers\\FeaturesManager' => __DIR__ . '/../..' . '/src/Managers/FeaturesManager.php',
        'MuzaPay\\Managers\\PostTypeManager' => __DIR__ . '/../..' . '/src/Managers/PostTypeManager.php',
        'MuzaPay\\Managers\\RepositoryManager' => __DIR__ . '/../..' . '/src/Managers/RepositoryManager.php',
        'MuzaPay\\Models\\OrderModel' => __DIR__ . '/../..' . '/src/Models/OrderModel.php',
        'MuzaPay\\Models\\ProductModel' => __DIR__ . '/../..' . '/src/Models/ProductModel.php',
        'MuzaPay\\Plugin' => __DIR__ . '/../..' . '/src/Plugin.php',
        'MuzaPay\\PostTypes\\ProductPostType' => __DIR__ . '/../..' . '/src/PostTypes/ProductPostType.php',
        'MuzaPay\\Repositories\\OrderRepository' => __DIR__ . '/../..' . '/src/Repositories/OrderRepository.php',
        'MuzaPay\\Repositories\\ProductRepository' => __DIR__ . '/../..' . '/src/Repositories/ProductRepository.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8d0dc70d94eb20d3d4c46917dac00800::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8d0dc70d94eb20d3d4c46917dac00800::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8d0dc70d94eb20d3d4c46917dac00800::$classMap;

        }, null, ClassLoader::class);
    }
}
