<?php

// This file `jetpack_autoload_classmap.php` was auto generated by automattic/jetpack-autoloader.

$vendorDir = dirname(__DIR__);
$baseDir   = dirname($vendorDir);

return array(
	'Appsero\\Client' => array(
		'version' => '2.0.3.0',
		'path'    => $vendorDir . '/appsero/client/src/Client.php'
	),
	'Appsero\\Insights' => array(
		'version' => '2.0.3.0',
		'path'    => $vendorDir . '/appsero/client/src/Insights.php'
	),
	'Appsero\\License' => array(
		'version' => '2.0.3.0',
		'path'    => $vendorDir . '/appsero/client/src/License.php'
	),
	'Autoloader' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-autoloader.php'
	),
	'Autoloader_Handler' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-autoloader-handler.php'
	),
	'Autoloader_Locator' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-autoloader-locator.php'
	),
	'Automattic\\Jetpack\\Autoloader\\AutoloadFileWriter' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadFileWriter.php'
	),
	'Automattic\\Jetpack\\Autoloader\\AutoloadGenerator' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadGenerator.php'
	),
	'Automattic\\Jetpack\\Autoloader\\AutoloadProcessor' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/AutoloadProcessor.php'
	),
	'Automattic\\Jetpack\\Autoloader\\CustomAutoloaderPlugin' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/CustomAutoloaderPlugin.php'
	),
	'Automattic\\Jetpack\\Autoloader\\ManifestGenerator' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/ManifestGenerator.php'
	),
	'Container' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-container.php'
	),
	'Hook_Manager' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-hook-manager.php'
	),
	'Latest_Autoloader_Guard' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-latest-autoloader-guard.php'
	),
	'Manifest_Reader' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-manifest-reader.php'
	),
	'Optemiz\\AWO\\Admin' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/Admin.php'
	),
	'Optemiz\\AWO\\Admin_Menu' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/Admin_Menu.php'
	),
	'Optemiz\\AWO\\Admin_Notices' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/Admin_Notices.php'
	),
	'Optemiz\\AWO\\Admin_Page' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/Admin_Page.php'
	),
	'Optemiz\\AWO\\Assets' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/Assets.php'
	),
	'Optemiz\\AWO\\AutoComplete_Orders' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/AutoComplete_Orders.php'
	),
	'Optemiz\\AWO\\Frontend' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/Frontend.php'
	),
	'Optemiz\\AWO\\Metaboxes' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/Metaboxes.php'
	),
	'Optemiz\\AWO\\Settings' => array(
		'version' => 'dev-main',
		'path'    => $baseDir . '/includes/Settings.php'
	),
	'Optemiz\\Dashboard\\AbstractField' => array(
		'version' => '1.0.8.0',
		'path'    => $vendorDir . '/optemiz/dashboard/includes/AbstractField.php'
	),
	'Optemiz\\Dashboard\\AbstractTab' => array(
		'version' => '1.0.8.0',
		'path'    => $vendorDir . '/optemiz/dashboard/includes/AbstractTab.php'
	),
	'Optemiz\\Dashboard\\Field' => array(
		'version' => '1.0.8.0',
		'path'    => $vendorDir . '/optemiz/dashboard/includes/Field.php'
	),
	'Optemiz\\Dashboard\\Header' => array(
		'version' => '1.0.8.0',
		'path'    => $vendorDir . '/optemiz/dashboard/includes/Header.php'
	),
	'Optemiz\\Dashboard\\Settings' => array(
		'version' => '1.0.8.0',
		'path'    => $vendorDir . '/optemiz/dashboard/includes/Settings.php'
	),
	'Optemiz\\Dashboard\\Sidebar' => array(
		'version' => '1.0.8.0',
		'path'    => $vendorDir . '/optemiz/dashboard/includes/Sidebar.php'
	),
	'Optemiz\\Dashboard\\SubTab' => array(
		'version' => '1.0.8.0',
		'path'    => $vendorDir . '/optemiz/dashboard/includes/SubTab.php'
	),
	'Optemiz\\Dashboard\\Tab' => array(
		'version' => '1.0.8.0',
		'path'    => $vendorDir . '/optemiz/dashboard/includes/Tab.php'
	),
	'PHP_Autoloader' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-php-autoloader.php'
	),
	'Path_Processor' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-path-processor.php'
	),
	'Plugin_Locator' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-plugin-locator.php'
	),
	'Plugins_Handler' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-plugins-handler.php'
	),
	'Shutdown_Handler' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-shutdown-handler.php'
	),
	'Version_Loader' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-version-loader.php'
	),
	'Version_Selector' => array(
		'version' => '3.1.3',
		'path'    => $vendorDir . '/automattic/jetpack-autoloader/src/class-version-selector.php'
	),
);
