<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdCaptcha\\Instantiate' => $baseDir . '/src/Instantiate.php',
    'AdCaptcha\\Plugin\\AdCaptchaPlugin' => $baseDir . '/src/Plugin/AdCaptchaPlugin.php',
    'AdCaptcha\\Plugin\\Comments' => $baseDir . '/src/Plugin/Comments.php',
    'AdCaptcha\\Plugin\\ContactForm7\\Forms' => $baseDir . '/src/Plugin/ContactForm7/Forms.php',
    'AdCaptcha\\Plugin\\Elementor\\Forms' => $baseDir . '/src/Plugin/Elementor/Forms.php',
    'AdCaptcha\\Plugin\\FluentForms\\AdCaptchaElements' => $baseDir . '/src/Plugin/FluentForms/AdCaptchaElements.php',
    'AdCaptcha\\Plugin\\FluentForms\\Forms' => $baseDir . '/src/Plugin/FluentForms/Forms.php',
    'AdCaptcha\\Plugin\\Login' => $baseDir . '/src/Plugin/Login.php',
    'AdCaptcha\\Plugin\\Mailchimp\\Forms' => $baseDir . '/src/Plugin/Mailchimp/Forms.php',
    'AdCaptcha\\Plugin\\NinjaForms\\AdcaptchaField' => $baseDir . '/src/Plugin/NinjaForms/AdcaptchaField.php',
    'AdCaptcha\\Plugin\\NinjaForms\\Forms' => $baseDir . '/src/Plugin/NinjaForms/Forms.php',
    'AdCaptcha\\Plugin\\PasswordReset' => $baseDir . '/src/Plugin/PasswordReset.php',
    'AdCaptcha\\Plugin\\Registration' => $baseDir . '/src/Plugin/Registration.php',
    'AdCaptcha\\Plugin\\WPForms\\AdCAPTCHA_WPForms_Field' => $baseDir . '/src/Plugin/WPForms/AdCAPTCHA_WPForms_Field.php',
    'AdCaptcha\\Plugin\\WPForms\\Forms' => $baseDir . '/src/Plugin/WPForms/Forms.php',
    'AdCaptcha\\Plugin\\Woocommerce\\Checkout' => $baseDir . '/src/Plugin/Woocommerce/Checkout.php',
    'AdCaptcha\\Plugin\\Woocommerce\\Login' => $baseDir . '/src/Plugin/Woocommerce/Login.php',
    'AdCaptcha\\Plugin\\Woocommerce\\PasswordReset' => $baseDir . '/src/Plugin/Woocommerce/PasswordReset.php',
    'AdCaptcha\\Plugin\\Woocommerce\\Registration' => $baseDir . '/src/Plugin/Woocommerce/Registration.php',
    'AdCaptcha\\Settings\\Advanced' => $baseDir . '/src/Settings/Advanced.php',
    'AdCaptcha\\Settings\\General' => $baseDir . '/src/Settings/General.php',
    'AdCaptcha\\Settings\\Plugins' => $baseDir . '/src/Settings/Plugins.php',
    'AdCaptcha\\Settings\\Settings' => $baseDir . '/src/Settings/Settings.php',
    'AdCaptcha\\Widget\\AdCaptcha' => $baseDir . '/src/Widget/AdCaptcha.php',
    'AdCaptcha\\Widget\\Verify' => $baseDir . '/src/Widget/Verify.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
