<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbe8ae1f5c343206c3a94595067311712
{
    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Pagup\\TikTokButton\\Controllers\\ButtonController' => __DIR__ . '/../..' . '/admin/controllers/ButtonController.php',
        'Pagup\\TikTokButton\\Controllers\\SettingsController' => __DIR__ . '/../..' . '/admin/controllers/SettingsController.php',
        'Pagup\\TikTokButton\\Core\\Asset' => __DIR__ . '/../..' . '/admin/core/Asset.php',
        'Pagup\\TikTokButton\\Core\\Option' => __DIR__ . '/../..' . '/admin/core/Option.php',
        'Pagup\\TikTokButton\\Core\\Plugin' => __DIR__ . '/../..' . '/admin/core/Plugin.php',
        'Pagup\\TikTokButton\\Core\\Request' => __DIR__ . '/../..' . '/admin/core/Request.php',
        'Pagup\\TikTokButton\\Settings' => __DIR__ . '/../..' . '/admin/Settings.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitbe8ae1f5c343206c3a94595067311712::$classMap;

        }, null, ClassLoader::class);
    }
}
