<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8090253aa1337032da9d0bf1809a0bf0
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WCPress\\EasyMenuManager\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WCPress\\EasyMenuManager\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8090253aa1337032da9d0bf1809a0bf0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8090253aa1337032da9d0bf1809a0bf0::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8090253aa1337032da9d0bf1809a0bf0::$classMap;

        }, null, ClassLoader::class);
    }
}
